#!/usr/bin/env bash
set -e

mkdir -p dist

cat \
  src/config.js \
  src/util.js \
  src/features/preserve-scroll-on-refresh.js \
  src/features/modal-scroll-restore.js \
  src/features/ktl-hide-show-state.js \
  src/features/global-styles.js \
  src/features/scene-tweaks.js \
  src/features/percent-field-format.js \
  src/features/inline-form-recompose.js \
  src/features/inline-edit-checkbox-layout.js \
  src/features/extract-hsv-color.js \
  src/features/ktl-accordion/ktl-accordion.js \
  src/features/accordion-menu-inject.js \
  src/features/workflow-stepper.js \
  src/features/ratking/modal-backdrop-click-disable.js \
  src/features/ratking/default-field-values.js \
  src/features/ratking/post-inline-edit-behavior.js \
  src/features/ratking/timepicker-init.js \
  src/features/ratking/discount-copy-tweaks.js \
  src/features/ratking/hash-bump-record-update.js \
  src/features/ratking/scene-776-stub.js \
  src/features/proposal-grid.js \
  src/features/proposal-pdf-export.js \
  src/features/published-proposal-render.js \
  src/features/bid-items-grid.js \
  src/features/bid-review/config.js \
  src/features/bid-review/styles.js \
  src/features/bid-review/adapters.js \
  src/features/bid-review/transform.js \
  src/features/bid-review/render.js \
  src/features/bid-review/actions.js \
  src/features/bid-review/change-requests.js \
  src/features/bid-review/init.js \
  src/features/sales-revision-column.js \
  src/features/group-collapse.js \
  src/features/select-all-checkboxes.js \
  src/features/SOW-line-item-DTO-bucket-field-visibility.js \
  src/features/SOW-line-item-DTO-bucket-field-visibility_view_3451.js \
  src/features/highlight-duplicate-cells.js \
  src/features/replace-content-with-icon.js \
  src/features/change-record-limit.js \
  src/features/SURVEY_lineitem_conditional-field-grayout.js \
  src/features/SOW_lineitem_conditional-field-grayout.js \
  src/features/sync-checkboxes \
  src/features/survey-form-drag-drop-files.js \
  src/features/hide-navigation.js \
  src/features/calc-install-fee-adjustment.js \
  src/features/instructions-placement.js \
  src/features/sales-edit-proposal-refresh-controls.js \
  src/features/exception-grid-handler.js \
  src/features/set_unified_product_field.js \
  src/features/filter-products-by-bucket.js \
  src/features/force-negative-display.js \
  src/features/refresh-on-inline-edit.js \
  src/features/refresh-view-on-form-submit.js \
  src/features/bucket-field-visibility_add-product.js \
  src/features/bucket-field-visibility_add-survey-bid-item.js \
  src/features/style-detail-labels.js \
  src/features/gtm-inject.js \
  src/features/jotform-embed-sow-photos.js \
  src/features/edit-button-group-header.js \
  src/features/inline-photo-row.js \
  src/features/boolean-chips.js \
  src/features/delete-intercept.js \
  src/features/connected-records.js \
  src/features/device-worksheet.js \
  src/features/sales-change-request/config.js \
  src/features/sales-change-request/state.js \
  src/features/sales-change-request/styles.js \
  src/features/sales-change-request/change-detection.js \
  src/features/sales-change-request/modals.js \
  src/features/sales-change-request/payload.js \
  src/features/sales-change-request/render.js \
  src/features/sales-change-request/submit.js \
  src/features/sales-change-request/revision-inject.js \
  src/features/sales-change-request/init.js \
  src/features/bid-revision-inject.js \
  src/features/revision-accept-reject.js \
  src/features/preview-proposal-btn.js \
  src/features/create-sow-option-btn.js \
  src/features/import-unique-items-btn.js \
  src/features/hide-self-row.js \
  src/features/hide-view-conditional.js \
  src/features/survey-worksheet-pdf-export.js \
  src/features/connected-device-bid-check.js \
  src/features/default-sort.js \
  src/features/mirror-connection-sync.js \
  src/features/grid-direct-edit.js \
  src/features/dynamic-cell-colors.js \
  src/features/revenue-tier-progress.js \
  src/features/legacy/checkbox-grid.field_739.js \
  src/features/legacy/expand-collapse-legacy-function.js \
  src/features/legacy/add-checkboxes.js \
  src/features/legacy/get-tl-photos.js \
  > dist/knack-bundle.js

echo "✔ Built dist/knack-bundle.js"
