#!/usr/bin/env bash
set -e

mkdir -p dist

# Concatenate all source files into a temp bundle, then minify with
# esbuild.  No transpilation beyond what --target=es2015 implies — we
# only want whitespace/comment removal and local-identifier mangling.
# Globals (window.SCW, Knack, $, jQuery) are preserved because they're
# accessed via property paths that esbuild leaves alone.
TMP_BUNDLE="$(mktemp -t knack-bundle.XXXXXX.js)"
trap 'rm -f "$TMP_BUNDLE"' EXIT

cat \
  src/config.js \
  src/util.js \
  src/features/patch-jquery-delegate-matching.js \
  src/features/session-timeout.js \
  src/features/_design-tokens.js \
  src/features/sow-color.js \
  src/features/_render-totals-guard.js \
  src/features/_toolbar-registry.js \
  src/features/_v2-scroll-anchor.js \
  src/features/_scroll-spy.js \
  src/features/disable-scroll-restoration.js \
  src/features/preserve-scroll-on-refresh.js \
  src/features/modal-refresh-redirect.js \
  src/features/modal-scroll-restore.js \
  src/features/ktl-hide-show-state.js \
  src/features/global-styles.js \
  src/features/google-places-pac-watchdog.js \
  src/features/hide-data-source-views.js \
  src/features/scene-tweaks.js \
  src/features/percent-field-format.js \
  src/features/inline-form-recompose.js \
  src/features/inline-edit-checkbox-layout.js \
  src/features/extract-hsv-color.js \
  src/features/heavy-grid-perf.js \
  src/features/ktl-accordion/ktl-accordion.js \
  src/features/accordion-menu-inject.js \
  src/features/workflow-stepper.js \
  src/features/survey-request-cards.js \
  src/features/accordion-section-icons.js \
  src/features/ratking/modal-backdrop-click-disable.js \
  src/features/ratking/default-field-values.js \
  src/features/ratking/post-inline-edit-behavior.js \
  src/features/ratking/timepicker-init.js \
  src/features/ratking/discount-copy-tweaks.js \
  src/features/ratking/hash-bump-record-update.js \
  src/features/ratking/scene-776-stub.js \
  src/features/modal-form-connection-sync.js \
  src/features/proposal-grid-v2.js \
  src/features/survey-review-grid.js \
  src/features/proposal-pdf-export.js \
  src/features/proposal-preview-images.js \
  src/features/proposal-preview-expiration.js \
  src/features/published-proposal-render.js \
  src/features/secure-proposal-link.js \
  src/features/bid-items-grid.js \
  src/features/bid-review/config.js \
  src/features/bid-review/styles.js \
  src/features/bid-review/adapters.js \
  src/features/bid-review/transform.js \
  src/features/bid-review/render.js \
  src/features/bid-review/actions.js \
  src/features/bid-review/change-requests.js \
  src/features/bid-review/init.js \
  src/features/bid-review-v2/config.js \
  src/features/bid-review-v2/styles.js \
  src/features/bid-review-v2/state.js \
  src/features/bid-review-v2/data.js \
  src/features/bid-review-v2/transform.js \
  src/features/bid-review-v2/warnings.js \
  src/features/bid-review-v2/column-collapse.js \
  src/features/bid-review-v2/basis-filter.js \
  src/features/bid-review-v2/toolbar.js \
  src/features/bid-review-v2/search.js \
  src/features/bid-review-v2/edit.js \
  src/features/bid-review-v2/card.js \
  src/features/mdf-edit-core.js \
  src/features/bid-review-v2/mdf-manage.js \
  src/features/bid-review-v2/bulk-cr.js \
  src/features/bid-review-v2/render.js \
  src/features/bid-review-v2/init.js \
  src/features/sub-bid-diff/config.js \
  src/features/sub-bid-diff/styles.js \
  src/features/sub-bid-diff/render.js \
  src/features/sub-bid-diff/pdf-html.js \
  src/features/sub-bid-diff/init.js \
  src/features/sow-margin-cascade.js \
  src/features/sow-item-tray.js \
  src/features/sales-revision-column.js \
  src/features/group-collapse.js \
  src/features/sow-filter-pills.js \
  src/features/select-all-checkboxes.js \
  src/features/bulk-delete-confirm.js \
  src/features/bulk-add-mounting-box.js \
  src/features/SOW-line-item-DTO-bucket-field-visibility.js \
  src/features/SOW-line-item-DTO-bucket-field-visibility_view_3451.js \
  src/features/highlight-duplicate-cells.js \
  src/features/change-record-limit.js \
  src/features/SURVEY_lineitem_conditional-field-grayout.js \
  src/features/SOW_lineitem_conditional-field-grayout.js \
  src/features/sync-checkboxes \
  src/features/survey-form-drag-drop-files.js \
  src/features/hide-navigation.js \
  src/features/nav-knack2-highlight.js \
  src/features/strip-register-buttons.js \
  src/features/calc-install-fee-adjustment.js \
  src/features/instructions-placement.js \
  src/features/sales-edit-proposal-refresh-controls.js \
  src/features/exception-grid-handler.js \
  src/features/set_unified_product_field.js \
  src/features/filter-products-by-bucket.js \
  src/features/filter-mdf-idf-by-view.js \
  src/features/force-negative-display.js \
  src/features/refresh-view-on-form-submit.js \
  src/features/bucket-field-visibility_add-product.js \
  src/features/bucket-field-visibility_add-survey-bid-item.js \
  src/features/style-detail-labels.js \
  src/features/gtm-inject.js \
  src/features/jotform-embed-sow-photos.js \
  src/features/bulk-upload.js \
  src/features/edit-button-group-header.js \
  src/features/inline-photo-row.js \
  src/features/mdf-summary-panel.js \
  src/features/boolean-chips.js \
  src/features/delete-intercept.js \
  src/features/connected-records.js \
  src/features/device-worksheet.js \
  src/features/survey-bid-validate.js \
  src/features/device-worksheet-expand-all.js \
  src/features/device-worksheet-photo-toggle.js \
  src/features/device-worksheet-toolbar.js \
  src/features/device-worksheet-sort.js \
  src/features/install-config-subpanel.js \
  src/features/install-as-quoted-panel.js \
  src/features/deploy-page-nav.js \
  src/features/qa-popover.js \
  src/features/photo-edit-panel.js \
  src/features/config-qa-popover.js \
  src/features/closeout-deliverables.js \
  src/features/chit-bulk-edit-fix.js \
  src/features/sales-change-request/config.js \
  src/features/sales-change-request/state.js \
  src/features/sales-change-request/styles.js \
  src/features/sales-change-request/change-detection.js \
  src/features/sales-change-request/modals.js \
  src/features/sales-change-request/payload.js \
  src/features/sales-change-request/render.js \
  src/features/sales-change-request/submit.js \
  src/features/sales-change-request/revision-inject.js \
  src/features/sales-change-request/init.js \
  src/features/bid-revision-inject.js \
  src/features/sub-variant-bid.js \
  src/features/revision-accept-reject.js \
  src/features/proposal-type-chip.js \
  src/features/published-quote-info.js \
  src/features/proposal-expiration-mirror.js \
  src/features/ops-review-pill.js \
  src/features/pq-expiration-edit.js \
  src/features/sow-grid-cards.js \
  src/features/mdf-idf-cards.js \
  src/features/files-gallery.js \
  src/features/photo-grid-manager.js \
  src/features/survey-request-header.js \
  src/features/ops-stepper.js \
  src/features/sales-stepper.js \
  src/features/published-quote-on-proposal-page.js \
  src/features/published-proposal-sow-card.js \
  src/features/preview-proposal-btn.js \
  src/features/create-sow-option-btn.js \
  src/features/clone-sow-to-project.js \
  src/features/import-unique-items-btn.js \
  src/features/hide-self-row.js \
  src/features/hide-view-conditional.js \
  src/features/internal-only-views.js \
  src/features/hide-views-below-bom.js \
  src/features/survey-worksheet-pdf-export.js \
  src/features/sub-portal-survey-request-export.js \
  src/features/sub-bid-submit-gate.js \
  src/features/sow-pdf-stepper.js \
  src/features/connected-device-bid-check.js \
  src/features/missing-connection-warn.js \
  src/features/worksheet-warning-summary.js \
  src/features/default-sort.js \
  src/features/mirror-connection-sync.js \
  src/features/connected-to-readonly.js \
  src/features/calc-field-nudge.js \
  src/features/address-complete-guard.js \
  src/features/connection-picker.js \
  src/features/connected-device-count-on-form.js \
  src/features/grid-direct-edit.js \
  src/features/dynamic-cell-colors.js \
  src/features/revenue-tier-progress.js \
  src/features/legacy/checkbox-grid.field_739.js \
  src/features/legacy/expand-collapse-legacy-function.js \
  src/features/legacy/add-checkboxes.js \
  src/features/legacy/get-tl-photos.js \
  src/features/worksheet-v2/config.js \
  src/features/worksheet-v2/styles.js \
  src/features/worksheet-v2/state.js \
  src/features/worksheet-v2/data.js \
  src/features/worksheet-v2/groups.js \
  src/features/worksheet-v2/card.js \
  src/features/worksheet-v2/photos.js \
  src/features/worksheet-v2/warnings.js \
  src/features/worksheet-v2/summary.js \
  src/features/worksheet-v2/picker.js \
  src/features/worksheet-v2/edit.js \
  src/features/worksheet-v2/audit-log.js \
  src/features/worksheet-v2/mdf-notes.js \
  src/features/worksheet-v2/render.js \
  src/features/worksheet-v2/toolbar.js \
  src/features/worksheet-v2/sort.js \
  src/features/worksheet-v2/sow-filter.js \
  src/features/worksheet-v2/search.js \
  src/features/worksheet-v2/native-filter.js \
  src/features/worksheet-v2/bulk.js \
  src/features/worksheet-v2/prefill-accessory-parent.js \
  src/features/worksheet-v2/change-requests.js \
  src/features/worksheet-v2/poll.js \
  src/features/worksheet-v2/init.js \
  src/features/worksheet-v2/co-adopt.js \
  src/features/worksheet-v2/co-remove.js \
  src/features/worksheet-v2/co-add-item-form.js \
  src/features/worksheet-v2/co-scene-header.js \
  src/features/worksheet-v2/co-value.js \
  src/features/worksheet-v2/co-sub-lock.js \
  src/features/worksheet-v2/co-ops-lock.js \
  src/features/worksheet-v2/co-review-diff.js \
  src/features/accessory-edit-modal.js \
  src/features/survey-report-photo-lightbox.js \
  src/features/sales-change-request/render-v2.js \
  src/features/deliverables-worksheet.js \
  src/features/customer-questionnaire.js \
  src/features/customer-account-link.js \
  src/features/customer-questionnaire-scene.js \
  src/features/client-questionnaire-list.js \
  src/features/client-sites-list.js \
  src/features/send-coc-button.js \
  src/features/regenerate-closeout-docs.js \
  src/features/co-header-card.js \
  src/features/co-stage-strip.js \
  src/features/questionnaire-deployment-audit.js \
  src/features/acceptance-card.js \
  src/features/questionnaire-card.js \
  src/features/co-cards.js \
  src/features/other-files-gallery.js \
  src/features/resend-credentials-btn.js \
  > "$TMP_BUNDLE"

UNMIN_BYTES=$(wc -c < "$TMP_BUNDLE" | tr -d ' ')

npx --yes esbuild "$TMP_BUNDLE" \
  --minify \
  --target=es2015 \
  --legal-comments=none \
  --outfile=dist/knack-bundle.js \
  --log-level=warning

MIN_BYTES=$(wc -c < dist/knack-bundle.js | tr -d ' ')
RATIO=$(awk -v a="$MIN_BYTES" -v b="$UNMIN_BYTES" 'BEGIN { printf "%.1f", (a / b) * 100 }')
echo "✔ Built dist/knack-bundle.js  (${UNMIN_BYTES} → ${MIN_BYTES} bytes, ${RATIO}%)"
