/*** BID REVIEW — STYLES ***/
/**
 * Injects all CSS for the Bid Review Matrix.
 * Guarded by a unique style-element ID to prevent duplicates.
 *
 * Reads : SCW.bidReview.CONFIG.cssId
 * Writes: SCW.bidReview.injectStyles()
 */
(function () {
  'use strict';

  var ns  = (window.SCW.bidReview = window.SCW.bidReview || {});
  var CFG = ns.CONFIG;

  ns.injectStyles = function injectStyles() {
    if (document.getElementById(CFG.cssId)) return;

    var css = [

      /* ── container ─────────────────────────────────────────── */
      '.scw-bid-review {',
      '  font: 13px/1.4 system-ui, -apple-system, sans-serif;',
      '  color: #1e293b;',
      '  overflow-x: auto;',
      '  -webkit-overflow-scrolling: touch;',
      '  padding: 0;',
      '  margin: 0;',
      '}',

      /* ── SOW sections ────────────────────────────────────────── */
      '.scw-bid-review__sow-section {',
      '  margin-bottom: 24px;',
      '  border: 1px solid #e2e8f0;',
      '  border-radius: 6px;',
      '  overflow: hidden;',
      '}',

      '.scw-bid-review__sow-title {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 10px;',
      '  padding: 10px 12px;',
      '  background: #1e293b;',
      '  color: #fff;',
      '  cursor: pointer;',
      '  user-select: none;',
      '  -webkit-user-select: none;',
      '}',

      '.scw-bid-review__sow-title:hover {',
      '  background: #334155;',
      '}',

      '.scw-bid-review__sow-chevron {',
      '  display: inline-flex;',
      '  transition: transform .2s ease;',
      '}',

      '.scw-bid-review__sow-section--collapsed .scw-bid-review__sow-chevron {',
      '  transform: rotate(-90deg);',
      '}',

      '.scw-bid-review__sow-body {',
      '  overflow: hidden;',
      '}',

      '.scw-bid-review__sow-section--collapsed .scw-bid-review__sow-body {',
      '  display: none;',
      '}',

      '.scw-bid-review__sow-title-text {',
      '  font-size: 14px;',
      '  font-weight: 700;',
      '}',

      '.scw-bid-review__sow-title-count {',
      '  font-size: 11px;',
      '  font-weight: 400;',
      '  color: #94a3b8;',
      '}',

      /* ── SOW status bar (lives inside the SOW header cell, rowspan=2) ── */
      '.scw-bid-review__sow-status {',
      '  display: flex; flex-direction: column; gap: 8px;',
      '  align-items: stretch;',
      '  height: 100%;',
      '}',
      /* The status bar sits inside a <td>, so reset any block-level
         padding / background from earlier iterations and let the cell
         own the framing. ops-review-pill CSS provides the inner block
         layout (pill, margin warning, proposal block). */
      '.scw-bid-review__sow-status .scw-ops-block {',
      '  display: flex; flex-direction: column; gap: 6px;',
      '  align-items: flex-start;',
      '}',
      /* SOW header cell — gives the status bar room to breathe. Vertical
         alignment top so the bar starts at the same y-line as the bid
         columns badges. */
      'td.scw-bid-review__sow-header-cell {',
      '  vertical-align: top; padding: 8px 10px; min-width: 240px;',
      '  height: 1px;',  // collapse to content baseline so child height:100% works
      '}',
      /* Survey Costs / Margin — stacked vertically (one per line). */
      '.scw-bid-review__sow-metrics {',
      '  display: flex; flex-direction: column; gap: 4px;',
      '  align-items: stretch;',
      '}',
      '.scw-bid-review__sow-metric {',
      '  display: flex; align-items: center; gap: 8px;',
      '  justify-content: space-between;',
      '  font: 600 12px/1.2 system-ui, sans-serif; color: #334155;',
      '}',
      '.scw-bid-review__sow-metric-label {',
      '  text-transform: uppercase; letter-spacing: 0.04em;',
      '  font-size: 10.5px; color: #64748b;',
      '}',
      '.scw-bid-review__sow-metric-value {',
      '  font-size: 13px; color: #0f172a;',
      '}',
      '.scw-bid-review__sow-metric-input {',
      '  width: 110px; padding: 4px 6px;',
      '  border: 1px solid #cbd5e1; border-radius: 4px;',
      '  font: 500 12px/1.2 system-ui, sans-serif; color: #0f172a;',
      '  background: #fff;',
      '}',
      '.scw-bid-review__sow-metric-input:focus {',
      '  outline: none; border-color: #0d9488;',
      '  box-shadow: 0 0 0 2px rgba(13, 148, 136, 0.2);',
      '}',
      '.scw-bid-review__sow-metric-input--saving {',
      '  background: #fef3c7;',
      '}',
      '.scw-bid-review__sow-metric-input--saved {',
      '  background: #ecfdf5;',
      '}',
      /* Preview-Proposal pill inside the SOW status bar — restyled to
         match the .scw-bid-review__btn--adopt "Sync to SOW" button in
         the bid columns (same font / padding / border-radius / color). */
      '.scw-bid-review__sow-status .scw-ops-pill,',
      '.scw-bid-review__sow-status .scw-ops-pill:hover,',
      '.scw-bid-review__sow-status .scw-ops-pill:visited {',
      '  display: inline-flex; align-items: center; justify-content: center;',
      '  align-self: stretch; margin-top: auto;',  // bottom-align via flex auto-margin
      '  padding: 4px 8px;',
      '  border: none; border-radius: 4px;',
      '  font: 600 11px/1.2 system-ui, sans-serif;',
      '  background: #0891b2; color: #fff !important;',
      '  text-decoration: none; cursor: pointer;',
      '  white-space: nowrap; min-height: 0; gap: 4px;',
      '  transition: filter .15s;',
      '}',
      '.scw-bid-review__sow-status .scw-ops-pill:hover {',
      '  filter: brightness(0.92);',
      '}',
      /* Pending-state ("Processing X…") variant — keep the busy look so
         users still see the spinner instead of the action affordance. */
      '.scw-bid-review__sow-status .scw-ops-pill.is-pending {',
      '  background: #94a3b8; cursor: not-allowed;',
      '}',
      /* Hide the info-tooltip dot only when its data-scw-tip is empty —
         otherwise the auto-revert note dot would inherit the dark teal
         background and look out of place against the button. */
      '.scw-bid-review__sow-status .scw-ops-pill .scw-ops-info {',
      '  background: rgba(255,255,255,.2); color: #fff;',
      '}',
      /* "Add PM & Mobilization" button (lives inside the margin-low
         warning) — stretched to full width of the warning box. The
         ops-review-pill default sits left-aligned with max-content
         width; override both. */
      '.scw-bid-review__sow-status .scw-ops-margin-warning__btn {',
      '  flex: 0 0 100%; max-width: none; margin-left: 0; width: 100%;',
      '  justify-content: center; text-align: center;',
      '  white-space: normal;',
      '}',

      /* ── table ─────────────────────────────────────────────── */
      '.scw-bid-review__table {',
      '  width: 100%;',
      '  border-collapse: collapse;',
      '  table-layout: fixed;',
      '  min-width: 700px;',
      '}',

      /* ── header row ────────────────────────────────────────── */
      '.scw-bid-review__header-row th {',
      '  position: sticky;',
      '  top: 0;',
      '  z-index: 2;',
      '  background: #f8fafc;',
      '  border-bottom: 2px solid #cbd5e1;',
      '  padding: 10px 8px;',
      '  text-align: left;',
      '  vertical-align: top;',
      '  font-weight: 600;',
      '  font-size: 13px;',
      '}',

      '.scw-bid-review__sow-header {',
      '  width: 100px;',
      '  min-width: 80px;',
      '  text-align: center;',
      '}',

      /* SOW detail, bid columns, and change request column share equal width */
      '.scw-bid-review__sow-detail-header,',
      '.scw-bid-review__pkg-header,',
      '.scw-bid-review__actions-header {',
      '}',
      '.scw-bid-review__header-titles th.scw-bid-review__sow-detail-header {',
      '  text-align: center !important;',
      '  font-size: 12px !important;',
      '}',
      '.scw-bid-review__header-details .scw-bid-review__header-detail-cell {',
      '  text-align: center;',
      '  padding-top: 10px;',
      '}',

      /* ── unified column header (3-row layout) ─────────── */
      '.scw-bid-review__header-row th,',
      '.scw-bid-review__header-row td {',
      '  text-align: center;',
      '  vertical-align: middle;',
      '  padding: 4px 8px;',
      '}',
      '.scw-bid-review__header-titles th {',
      '  font-size: 12px !important;',
      '  font-weight: 700 !important;',
      '  text-transform: uppercase !important;',
      '  letter-spacing: .05em !important;',
      '  text-align: center !important;',
      '  color: #334155;',
      '  padding-top: 10px;',
      '  border-bottom: none;',
      '}',
      '.scw-bid-review__header-details td {',
      '  font-size: 11px;',
      '  color: #64748b;',
      '  border-bottom: none;',
      '  padding-top: 0;',
      '}',
      '.scw-bid-review__header-actions td {',
      '  padding-bottom: 8px;',
      '}',
      '.scw-bid-review__header-detail-cell {',
      '  text-align: center;',
      '}',
      '.scw-bid-review__header-action-cell {',
      '  text-align: center;',
      '}',
      '.scw-bid-review__header-action-cell .scw-bid-review__btn {',
      '  display: block;',
      '  width: 100%;',
      '  margin: 3px 0;',
      '}',
      '.scw-bid-review__col-status {',
      '  font-size: 10px;',
      '  line-height: 1;',
      '  margin-bottom: 2px;',
      '}',
      '.scw-bid-review__col-title {',
      '  font-size: 11px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: .05em;',
      '  color: #334155;',
      '}',
      '.scw-bid-review__col-subtitle {',
      '  font-size: 11px;',
      '  font-weight: 500;',
      '  color: #64748b;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  gap: 4px;',
      '  margin-top: 1px;',
      '}',
      '.scw-bid-review__col-links {',
      '  display: flex;',
      '  flex-direction: column;',
      '  align-items: center;',
      '  gap: 2px;',
      '  margin-top: 4px;',
      '}',
      '.scw-bid-review__col-buttons {',
      '  display: flex;',
      '  flex-direction: column;',
      '  align-items: center;',
      '  gap: 3px;',
      '  margin-top: 6px;',
      '}',

      /* ── package column header ─────────────────────────────── */

      '.scw-bid-review__pkg-name {',
      '  font-size: 14px;',
      '  font-weight: 700;',
      '  color: #0f172a;',
      '  margin-bottom: 4px;',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 6px;',
      '}',

      '.scw-bid-review__pdf-link {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  color: #dc2626;',
      '  opacity: .7;',
      '  transition: opacity 150ms ease;',
      '  flex-shrink: 0;',
      '}',
      '.scw-bid-review__pdf-link:hover { opacity: 1; }',
      '.scw-bid-review__pdf-link svg { display: block; width: 20px; height: 20px; }',

      '.scw-bid-review__cr-link {',
      '  display: block;',
      '  font-size: 11px;',
      '  font-weight: 600;',
      '  color: #dc6900;',
      '  margin-top: 4px;',
      '  text-decoration: none;',
      '}',
      '.scw-bid-review__cr-link:hover {',
      '  text-decoration: underline;',
      '  color: #b85700;',
      '}',

      '.scw-bid-review__pkg-counts {',
      '  font-size: 11px;',
      '  font-weight: 400;',
      '  color: #64748b;',
      '  margin-bottom: 6px;',
      '}',

      '.scw-bid-review__pkg-actions {',
      '  display: flex;',
      '  flex-direction: row;',
      '  gap: 4px;',
      '  margin-top: 4px;',
      '}',

      /* ── buttons ───────────────────────────────────────────── */
      '.scw-bid-review__btn {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  padding: 4px 8px;',
      '  border: none;',
      '  border-radius: 4px;',
      '  font: 600 11px/1.2 system-ui, sans-serif;',
      '  cursor: pointer;',
      '  transition: opacity .15s, filter .15s;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-review__btn:hover {',
      '  filter: brightness(0.92);',
      '}',

      '.scw-bid-review__btn--adopt {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--create {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--combo {',
      '  background: #7c3aed;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--skip {',
      '  background: #e2e8f0;',
      '  color: #475569;',
      '}',

      '.scw-bid-review__btn--revision {',
      '  background: #fbbf24;',
      '  color: #78350f;',
      '}',

      '.scw-bid-review__btn--change-req {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--change-edit {',
      '  background: #f59e0b;',
      '  color: #78350f;',
      '}',

      '.scw-bid-review__btn--remove-bid {',
      '  background: #fef2f2;',
      '  color: #dc2626;',
      '  border: 1px solid #fca5a5;',
      '}',

      '.scw-bid-review__toolbar {',
      '  display: flex;',
      '  justify-content: flex-end;',
      '  gap: 8px;',
      '  padding: 8px 4px;',
      '  margin-bottom: 4px;',
      '}',

      '.scw-bid-review__btn--create-sow {',
      '  background: #07467c;',
      '  color: #fff;',
      '  font-size: 13px;',
      '  padding: 8px 14px;',
      '}',

      '.scw-bid-review__btn--busy {',
      '  opacity: 0.5;',
      '  pointer-events: none;',
      '  cursor: default;',
      '}',

      '.scw-bid-review__btn--sm {',
      '  font-size: 10px;',
      '  padding: 3px 6px;',
      '}',

      /* ── collapsible group headers (accordion style) ────────── */
      '.scw-bid-review__group-header {',
      '  cursor: pointer;',
      '  user-select: none;',
      '  -webkit-user-select: none;',
      '}',

      '.scw-bid-review__group-header td {',
      '  position: relative;',
      '  background: #f1f5f9;',
      '  padding: 0;',
      '  font-weight: 700;',
      '  font-size: 13px;',
      '  color: #334155;',
      '  border-bottom: 1px solid #cbd5e1;',
      '  border-left: 4px solid #295f91;',
      '}',

      '.scw-bid-review__grp-inner {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 8px;',
      '  padding: 10px 12px 10px 12px;',
      '}',

      '.scw-bid-review__group-header:hover td {',
      '  background: #e8edf3;',
      '}',

      /* Chevron in group header */
      '.scw-bid-review__grp-chevron {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  flex: 0 0 auto;',
      '  color: #295f91;',
      '  transition: transform 220ms ease;',
      '}',

      '.scw-bid-review__group-header--collapsed .scw-bid-review__grp-chevron {',
      '  transform: rotate(-90deg);',
      '}',

      /* Title */
      '.scw-bid-review__grp-title {',
      '  flex: 1 1 auto;',
      '}',

      /* Count pill — mirrors KTL accordion count */
      '.scw-bid-review__grp-count {',
      '  display: inline-block;',
      '  padding: 2px 8px;',
      '  font-size: 11px;',
      '  font-weight: 600;',
      '  line-height: 1.4;',
      '  border-radius: 999px;',
      '  background: rgba(41, 95, 145, 0.12);',
      '  border: 1px solid rgba(41, 95, 145, 0.22);',
      '  color: #295f91;',
      '}',

      /* ── subgroup headers (proposalBucket within mdfIdf) ──── */
      '.scw-bid-review__subgroup-header td {',
      '  background: #f8fafc;',
      '  padding: 0;',
      '  border-bottom: 1px solid #e2e8f0;',
      '}',

      '.scw-bid-review__subgrp-inner {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 6px;',
      '  padding: 6px 12px 6px 28px;',
      '}',

      '.scw-bid-review__subgrp-title {',
      '  font-size: 12px;',
      '  font-weight: 600;',
      '  color: #475569;',
      '}',

      '.scw-bid-review__subgrp-count {',
      '  display: inline-block;',
      '  padding: 1px 6px;',
      '  font-size: 10px;',
      '  font-weight: 600;',
      '  line-height: 1.4;',
      '  border-radius: 999px;',
      '  background: #f1f5f9;',
      '  color: #64748b;',
      '}',

      /* ── data rows ─────────────────────────────────────────── */
      '.scw-bid-review__row td {',
      '  padding: 6px 8px;',
      '  border-bottom: 1px solid #e5e7eb;',
      '  vertical-align: top;',
      '}',

      '.scw-bid-review__row:nth-child(even) td {',
      '  background: #fafbfc;',
      '}',

      '.scw-bid-review__row:hover td {',
      '  background: #eff6ff;',
      '}',

      /* Click-to-expand row: cursor + a soft blue drop-shadow halo on
         the SOW columns (cells 1+2) that visually continues the panel\'s
         shadow above the row, so the data row + panel read as one unit. */
      '.scw-bid-review__row--expandable { cursor: pointer; }',
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(1),',
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(2) {',
      '  position: relative;',
      '  background: #fff !important;',
      '}',
      /* Top halo + outer side shadows. Side shadows match ws-card\'s
         left/right shadows but bumped 20% (0.315 → 0.378) so the left
         glow has a bit more presence than the panel\'s. */
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(1) {',
      '  box-shadow: 0 -18px 22px -10px rgba(2, 132, 199, 0.46),',
      '              -10px 14px 18px -10px rgba(2, 132, 199, 0.378);',
      '}',
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(2) {',
      '  box-shadow: 0 -18px 22px -10px rgba(2, 132, 199, 0.46),',
      '              10px 14px 18px -10px rgba(2, 132, 199, 0.378);',
      '}',

      /* Expand-row: hidden until the parent row is open. The injected
         worksheet card renders inside a mini-table so device-worksheet\'s
         <tr.scw-ws-row> structure stays valid. */
      '.scw-bid-review__expand-row { display: none; }',
      '.scw-bid-review__expand-row--open { display: table-row; }',
      '.scw-bid-review__expand-cell {',
      '  padding: 0 0 12px !important;',
      '  background: transparent;',
      '  border: none !important;',
      '}',
      /* Push the panel up to overlap with the data row above; square top
         corners + rounded bottom so it reads as integrated. Drop the
         worksheet card\'s default 1px border — the blue shadow alone
         frames the panel. */
      '.scw-bid-review__expand-cell .scw-ws-card {',
      '  margin-top: -5px;',
      '  border-radius: 0 0 8px 8px !important;',
      '  border: none !important;',
      '}',
      /* Sink the bid + actions cells of the expanded data row so the
         lifted panel above casts an inset shadow into them. */
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(n+3) {',
      '  box-shadow: inset 0 -8px 10px -6px rgba(2, 132, 199, 0.45);',
      '}',
      '.scw-bid-review__expand-table {',
      '  width: 100%;',
      '  border-collapse: collapse;',
      '  background: #fff;',
      '}',
      /* Tint the worksheet card\'s expanded drop shadow blue (overrides
         device-worksheet\'s default black/gray shadow). Big positive
         y-offset combined with negative spread keeps the shadow strictly
         below + to the sides — never on top. */
      '.scw-bid-review__expand-cell .scw-ws-card:has(.scw-ws-open),',
      '.scw-bid-review__expand-cell .scw-ws-card {',
      '  box-shadow: 0 16px 20px -10px rgba(2, 132, 199, 0.385),',
      '              -10px 14px 18px -10px rgba(2, 132, 199, 0.315),',
      '              10px 14px 18px -10px rgba(2, 132, 199, 0.315) !important;',
      '}',
      '.scw-bid-review__expand-table > tbody > tr > td {',
      '  padding: 0 !important;',
      '  border: none !important;',
      '}',
      '.scw-bid-review__expand-loading {',
      '  padding: 16px; color: #64748b; font-size: 13px; text-align: center;',
      '}',

      /* Hide view_3728 section once bid review is on the page — the
         comparison grid surfaces the same rows via expand-on-click. */
      'body.scw-bid-review-active #view_3728 {',
      '  display: none !important;',
      '}',
      'body.scw-bid-review-active .scw-ktl-accordion[data-view-key="view_3728"],',
      'body.scw-bid-review-active div.scw-ktl-accordion:has(> .scw-ktl-accordion__header[data-view-key="view_3728"]) {',
      '  display: none !important;',
      '}',

      /* ── SOW cell ──────────────────────────────────────────── */
      '.scw-bid-review__sow-cell {',
      '  font-weight: 600;',
      '  color: #1e293b;',
      '}',

      '.scw-bid-review__sow-cell--new {',
      '  font-weight: 600;',
      '  color: #1e293b;',
      '}',

      /* Row label (E-001 etc.) — block-level so the totals stack
         beneath it cleanly. */
      '.scw-bid-review__row-label {',
      '  font-weight: 600; color: #1e293b;',
      '}',

      /* Per-row Equipment + Install fee totals stacked under the
         row label. Each total = bold label on one line, $ value on
         the next. */
      '.scw-bid-review__row-totals {',
      '  display: flex; flex-direction: column; gap: 6px;',
      '  margin-top: 6px;',
      '}',
      '.scw-bid-review__row-total {',
      '  display: flex; flex-direction: column; gap: 0;',
      '  font: 500 11px/1.25 system-ui, sans-serif;',
      '  color: #64748b;',
      '}',
      '.scw-bid-review__row-total-label {',
      '  font-weight: 700;',
      '  color: #1e293b;',
      '}',
      '.scw-bid-review__row-total-value {',
      '  font-variant-numeric: tabular-nums;',
      '  color: #1e293b;',
      '}',

      '.scw-bid-review__new-badge {',
      '  display: inline-block;',
      '  padding: 1px 5px;',
      '  border-radius: 3px;',
      '  background: #2563eb;',
      '  color: #fff;',
      '  font-size: 9px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.5px;',
      '  vertical-align: middle;',
      '  margin-right: 4px;',
      '}',

      /* ── NO BID badge & row ──────────────────────────────────── */
      '.scw-bid-review__no-bid-badge {',
      '  display: inline-block;',
      '  padding: 1px 5px;',
      '  border-radius: 3px;',
      '  background: #dc2626;',
      '  color: #fff;',
      '  font-size: 9px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.5px;',
      '  vertical-align: middle;',
      '  margin-right: 4px;',
      '}',

      '.scw-bid-review__row--no-bid td {',
      '  background: #fef2f2 !important;',
      '}',

      '.scw-bid-review__row--no-bid:hover td {',
      '  background: #fee2e2 !important;',
      '}',

      /* ── SURVEY NO BID badge & row (on survey, not on any bid package) */
      '.scw-bid-review__survey-no-bid-badge {',
      '  display: inline-block;',
      '  padding: 1px 5px;',
      '  border-radius: 3px;',
      '  background: #d97706;',
      '  color: #fff;',
      '  font-size: 9px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.5px;',
      '  vertical-align: middle;',
      '  margin-right: 4px;',
      '}',

      '.scw-bid-review__row--survey-no-bid td {',
      '  background: #fffbeb !important;',
      '}',

      '.scw-bid-review__row--survey-no-bid:hover td {',
      '  background: #fef3c7 !important;',
      '}',

      /* ── package data cell ─────────────────────────────────── */
      '.scw-bid-review__cell-label {',
      '  font-size: 12px;',
      '  color: #334155;',
      '  margin-bottom: 2px;',
      '}',

      '.scw-bid-review__cell-values {',
      '  display: flex;',
      '  gap: 8px;',
      '  font-size: 12px;',
      '  color: #475569;',
      '}',

      '.scw-bid-review__cell-value {',
      '  font-weight: 600;',
      '  color: #0f172a;',
      '}',

      '.scw-bid-review__cell--missing {',
      '  color: #cbd5e1;',
      '  font-style: italic;',
      '  font-size: 12px;',
      '}',

      /* ── mismatch highlight (SOW vs Bid field pair differs) ── */
      '.scw-bid-review__cell--mismatch {',
      '  background: #fff7ed !important;',
      '  border-left: 3px solid #fb923c;',
      '}',

      /* ── per-field diff highlight (pinpoints WHICH values differ) ── */
      '.scw-bid-review__field-diff {',
      '  background: #fed7aa;',
      '  border-radius: 2px;',
      '  padding: 1px 4px;',
      '  box-decoration-break: clone;',
      '  -webkit-box-decoration-break: clone;',
      '}',

      '.scw-bid-review__cell-qty {',
      '  font-size: 11px;',
      '  color: #475569;',
      '  margin-top: 1px;',
      '}',

      '.scw-bid-review__cell-labor-desc {',
      '  font-size: 11px;',
      '  color: #475569;',
      '  margin-top: 1px;',
      '}',

      '.scw-bid-review__field-label {',
      '  font-weight: 600;',
      '  color: #64748b;',
      '}',

      '.scw-bid-review__cell-notes-divider {',
      '  border: none;',
      '  border-top: 1px solid #e2e8f0;',
      '  margin: 4px 0 2px;',
      '}',

      '.scw-bid-review__cell-notes {',
      '  font-size: 11px;',
      '  color: #64748b;',
      '  margin-top: 2px;',
      '}',

      '.scw-bid-review__cell-conn-device {',
      '  font-size: 11px;',
      '  color: #6366f1;',
      '  margin-top: 2px;',
      '  font-weight: 500;',
      '}',

      /* ── SOW detail cell ─────────────────────────────────────── */
      '.scw-bid-review__sow-detail {',
      '  vertical-align: top;',
      '  font-size: 12px;',
      '}',

      /* ── cabling chips ────────────────────────────────────────── */
      '.scw-bid-review__cabling-chip {',
      '  display: inline-block;',
      '  padding: 2px 7px;',
      '  border-radius: 3px;',
      '  font-size: 10px;',
      '  font-weight: 600;',
      '  margin-top: 4px;',
      '}',

      '.scw-bid-review__cabling-chip--on {',
      '  background: #dcfce7;',
      '  color: #166534;',
      '}',

      '.scw-bid-review__cabling-chip--off {',
      '  background: #f1f5f9;',
      '  color: #94a3b8;',
      '  font-weight: 400;',
      '}',

      /* ── status chips ──────────────────────────────────────── */
      '.scw-bid-review__chip {',
      '  display: inline-block;',
      '  padding: 1px 6px;',
      '  border-radius: 3px;',
      '  font-size: 10px;',
      '  font-weight: 600;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.3px;',
      '  margin-top: 3px;',
      '}',

      '.scw-bid-review__chip--matched {',
      '  background: #dcfce7;',
      '  color: #166534;',
      '}',

      '.scw-bid-review__chip--missing {',
      '  background: #fef3c7;',
      '  color: #92400e;',
      '}',

      '.scw-bid-review__chip--new {',
      '  background: #dbeafe;',
      '  color: #1e40af;',
      '}',

      '.scw-bid-review__chip--conflict {',
      '  background: #fee2e2;',
      '  color: #991b1b;',
      '}',

      /* ── row actions cell ──────────────────────────────────── */
      '.scw-bid-review__row-actions {',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 3px;',
      '}',

      /* ── action menus row ───────────────────────────────── */
      '.scw-bid-review__action-menus {',
      '  display: flex;',
      '  justify-content: flex-end;',
      '  gap: 4px;',
      '  margin-top: 2px;',
      '}',

      /* ── overflow menu (⋮ per action) ────────────────────── */
      '.scw-bid-review__overflow {',
      '  position: relative;',
      '}',

      '.scw-bid-review__overflow-trigger {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  gap: 3px;',
      '  padding: 3px 8px;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 4px;',
      '  background: #fff;',
      '  font: 600 10px/1.2 system-ui, sans-serif;',
      '  color: #475569;',
      '  cursor: pointer;',
      '  transition: background .15s, border-color .15s;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-review__overflow-trigger:hover {',
      '  background: #f1f5f9;',
      '  border-color: #94a3b8;',
      '}',

      '.scw-bid-review__overflow-dots {',
      '  font-size: 13px;',
      '  line-height: 1;',
      '  font-weight: 700;',
      '}',

      /* Trigger color variants */
      '.scw-bid-review__overflow-trigger--revise {',
      '  border-color: #93c5fd;',
      '  color: #1d4ed8;',
      '}',
      '.scw-bid-review__overflow-trigger--revise:hover {',
      '  background: #eff6ff;',
      '  border-color: #60a5fa;',
      '}',

      '.scw-bid-review__overflow-trigger--remove {',
      '  border-color: #fca5a5;',
      '  color: #dc2626;',
      '}',
      '.scw-bid-review__overflow-trigger--remove:hover {',
      '  background: #fef2f2;',
      '  border-color: #f87171;',
      '}',

      '.scw-bid-review__overflow-trigger--add {',
      '  border-color: #86efac;',
      '  color: #16a34a;',
      '}',
      '.scw-bid-review__overflow-trigger--add:hover {',
      '  background: #f0fdf4;',
      '  border-color: #4ade80;',
      '}',

      '.scw-bid-review__overflow-trigger--create {',
      '  border-color: #86efac;',
      '  color: #16a34a;',
      '}',
      '.scw-bid-review__overflow-trigger--create:hover {',
      '  background: #f0fdf4;',
      '  border-color: #4ade80;',
      '}',

      '.scw-bid-review__overflow-menu {',
      '  display: none;',
      '  position: absolute;',
      '  top: 100%;',
      '  right: 0;',
      '  z-index: 50;',
      '  margin-top: 2px;',
      '  min-width: 140px;',
      '  background: #fff;',
      '  border: 1px solid #e2e8f0;',
      '  border-radius: 6px;',
      '  box-shadow: 0 4px 12px rgba(0,0,0,.12);',
      '  padding: 4px 0;',
      '}',

      '.scw-bid-review__overflow--open .scw-bid-review__overflow-menu {',
      '  display: block;',
      '}',

      '.scw-bid-review__overflow-item {',
      '  display: block;',
      '  width: 100%;',
      '  text-align: left;',
      '  padding: 6px 12px;',
      '  border: none;',
      '  background: none;',
      '  font: 500 12px/1.3 system-ui, sans-serif;',
      '  color: #334155;',
      '  cursor: pointer;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-review__overflow-item:hover {',
      '  background: #f1f5f9;',
      '}',

      /* ── change request column header controls ────────────── */
      '.scw-bid-review__cr-col-title {',
      '  font-size: 13px;',
      '  font-weight: 700;',
      '  color: #0f172a;',
      '  margin-bottom: 4px;',
      '}',

      '.scw-bid-review__cr-col-actions {',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 3px;',
      '}',

      '.scw-bid-review__btn--cr-submit {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--cr-clear {',
      '  background: #e2e8f0;',
      '  color: #475569;',
      '}',

      /* ── change request cards (inline in actions column) ──── */
      '.scw-bid-cr-card {',
      '  background: #f0fdfa;',
      '  border: 1px solid #99f6e4;',
      '  border-left: 3px solid #0891b2;',
      '  border-radius: 4px;',
      '  padding: 5px 8px;',
      '  margin-top: 2px; margin-bottom: 2px;',
      '  font-size: 10px;',
      '  line-height: 1.35;',
      '  cursor: pointer;',
      '  transition: box-shadow .15s;',
      '}',
      '.scw-bid-cr-card:hover { box-shadow: 0 1px 4px rgba(0,0,0,.12); }',
      '.scw-bid-cr-card--removal {',
      '  background: #fef2f2;',
      '  border-color: #fca5a5;',
      '  border-left-color: #dc2626;',
      '}',
      '.scw-bid-cr-card--removal .scw-bid-cr-card__header {',
      '  color: #dc2626;',
      '}',
      '.scw-bid-cr-card--add {',
      '  background: #f0fdf4;',
      '  border-color: #86efac;',
      '  border-left-color: #16a34a;',
      '}',
      '.scw-bid-cr-card--add .scw-bid-cr-card__header {',
      '  color: #16a34a;',
      '}',

      '.scw-bid-cr-card__header {',
      '  font-weight: 700;',
      '  font-size: 9px;',
      '  text-transform: uppercase;',
      '  letter-spacing: .4px;',
      '  color: #0891b2;',
      '  margin-bottom: 3px;',
      '  position: relative;',
      '  padding-right: 14px;',
      '}',
      '.scw-bid-cr-card__dismiss {',
      '  position: absolute; top: -2px; right: -4px;',
      '  background: none; border: none; cursor: pointer;',
      '  font-size: 13px; line-height: 1; color: #94a3b8;',
      '  padding: 0 2px;',
      '}',
      '.scw-bid-cr-card__dismiss:hover { color: #dc2626; }',

      '.scw-bid-cr-card__item-label {',
      '  font-weight: 700;',
      '  font-size: 11px;',
      '  color: #0f172a;',
      '  margin-bottom: 2px;',
      '}',

      '.scw-bid-cr-card__row {',
      '  display: flex;',
      '  align-items: baseline;',
      '  gap: 3px;',
      '  padding: 1px 0;',
      '}',

      '.scw-bid-cr-card__label {',
      '  font-weight: 600;',
      '  color: #475569;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-cr-card__from {',
      '  color: #dc2626;',
      '  text-decoration: line-through;',
      '}',

      '.scw-bid-cr-card__arrow {',
      '  color: #94a3b8;',
      '  flex-shrink: 0;',
      '}',

      '.scw-bid-cr-card__to {',
      '  color: #059669;',
      '  font-weight: 600;',
      '}',

      '.scw-bid-cr-card__notes {',
      '  color: #64748b;',
      '  font-style: italic;',
      '  margin-top: 3px;',
      '  padding-top: 3px;',
      '  border-top: 1px solid #ccfbf1;',
      '}',

      /* ── empty & loading states ────────────────────────────── */
      '.scw-bid-review__empty-state {',
      '  text-align: center;',
      '  padding: 40px 20px;',
      '  color: #94a3b8;',
      '  font-size: 14px;',
      '}',

      '.scw-bid-review__loading {',
      '  text-align: center;',
      '  padding: 32px 20px;',
      '  color: #64748b;',
      '  font-size: 13px;',
      '}',

      '.scw-bid-review__loading::after {',
      '  content: "";',
      '  display: inline-block;',
      '  width: 14px;',
      '  height: 14px;',
      '  border: 2px solid #cbd5e1;',
      '  border-top-color: #3b82f6;',
      '  border-radius: 50%;',
      '  margin-left: 8px;',
      '  vertical-align: middle;',
      '  animation: scwBidSpin .7s linear infinite;',
      '}',

      '@keyframes scwBidSpin {',
      '  to { transform: rotate(360deg); }',
      '}',

      /* ── toast ──────────────────────────────────────────────── */
      '.scw-bid-review__toast {',
      '  position: fixed;',
      '  bottom: 24px;',
      '  left: 50%;',
      '  transform: translateX(-50%);',
      '  z-index: 100000;',
      '  padding: 10px 20px;',
      '  border-radius: 6px;',
      '  font: 600 13px/1.3 system-ui, sans-serif;',
      '  color: #fff;',
      '  box-shadow: 0 4px 16px rgba(0,0,0,0.25);',
      '  transition: opacity .3s;',
      '}',

      '.scw-bid-review__toast--success {',
      '  background: #16a34a;',
      '}',

      '.scw-bid-review__toast--error {',
      '  background: #dc2626;',
      '}',

      '.scw-bid-review__toast--info {',
      '  background: #2563eb;',
      '}',

      /* ── bid status bar ──────────────────────────────────── */
      '.scw-bid-review__status-bar {',
      '  display: flex;',
      '  flex-wrap: wrap;',
      '  gap: 10px;',
      '  margin-bottom: 14px;',
      '  padding: 10px 14px;',
      '  background: #f8fafc;',
      '  border: 1px solid #e2e8f0;',
      '  border-radius: 6px;',
      '}',
      '.scw-bid-review__status-chip {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 8px;',
      '  padding: 4px 0;',
      '}',
      '.scw-bid-review__status-pkg {',
      '  font-weight: 600;',
      '  font-size: 13px;',
      '  color: #334155;',
      '}',
      '.scw-bid-review__status-badge {',
      '  display: inline-block;',
      '  padding: 2px 10px;',
      '  border-radius: 12px;',
      '  font-size: 11px;',
      '  font-weight: 600;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.3px;',
      '  background: #e2e8f0;',
      '  color: #475569;',
      '}',
      '.scw-bid-review__status-badge[data-status="submitted"] {',
      '  background: #dcfce7;',
      '  color: #166534;',
      '}',
      '.scw-bid-review__status-badge[data-status="pending"] {',
      '  background: #fef3c7;',
      '  color: #92400e;',
      '}',
      '.scw-bid-review__status-badge[data-status="draft"] {',
      '  background: #dbeafe;',
      '  color: #1e40af;',
      '}',
      '.scw-bid-review__status-badge[data-status="rejected"] {',
      '  background: #fee2e2;',
      '  color: #991b1b;',
      '}',

    ].join('\n');

    var style = document.createElement('style');
    style.id = CFG.cssId;
    style.textContent = css;
    document.head.appendChild(style);
  };

})();
