/*** BID REVIEW — STYLES ***/
/**
 * Injects all CSS for the Bid Review Matrix.
 * Guarded by a unique style-element ID to prevent duplicates.
 *
 * Reads : SCW.bidReview.CONFIG.cssId
 * Writes: SCW.bidReview.injectStyles()
 */
(function () {
  'use strict';

  var ns  = (window.SCW.bidReview = window.SCW.bidReview || {});
  var CFG = ns.CONFIG;

  ns.injectStyles = function injectStyles() {
    if (document.getElementById(CFG.cssId)) return;

    var css = [

      /* ── container ─────────────────────────────────────────── */
      '.scw-bid-review {',
      '  font: 13px/1.4 system-ui, -apple-system, sans-serif;',
      '  color: #1e293b;',
      '  overflow-x: auto;',
      '  -webkit-overflow-scrolling: touch;',
      '  padding: 0;',
      '  margin: 0;',
      '}',

      /* ── SOW sections ────────────────────────────────────────── */
      '.scw-bid-review__sow-section {',
      '  margin-bottom: 24px;',
      '  border: 1px solid #e2e8f0;',
      '  border-radius: 6px;',
      '  overflow: hidden;',
      '}',

      '.scw-bid-review__sow-title {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 10px;',
      '  padding: 10px 12px;',
      '  background: #1e293b;',
      '  color: #fff;',
      '  cursor: pointer;',
      '  user-select: none;',
      '  -webkit-user-select: none;',
      '}',

      '.scw-bid-review__sow-title:hover {',
      '  background: #334155;',
      '}',

      '.scw-bid-review__sow-chevron {',
      '  display: inline-flex;',
      '  transition: transform .2s ease;',
      '}',

      '.scw-bid-review__sow-section--collapsed .scw-bid-review__sow-chevron {',
      '  transform: rotate(-90deg);',
      '}',

      '.scw-bid-review__sow-body {',
      '  overflow: hidden;',
      '}',

      '.scw-bid-review__sow-section--collapsed .scw-bid-review__sow-body {',
      '  display: none;',
      '}',

      '.scw-bid-review__sow-title-text {',
      '  font-size: 14px;',
      '  font-weight: 700;',
      '}',

      '.scw-bid-review__sow-title-count {',
      '  font-size: 11px;',
      '  font-weight: 400;',
      '  color: #94a3b8;',
      '}',

      /* ── SOW status bar (lives inside the SOW header cell, rowspan=2) ── */
      '.scw-bid-review__sow-status {',
      '  display: flex; flex-direction: column; gap: 8px;',
      '  align-items: stretch;',
      '  height: 100%;',
      '}',
      /* The status bar sits inside a <td>, so reset any block-level
         padding / background from earlier iterations and let the cell
         own the framing. ops-review-pill CSS provides the inner block
         layout (pill, margin warning, proposal block). */
      '.scw-bid-review__sow-status .scw-ops-block {',
      '  display: flex; flex-direction: column; gap: 6px;',
      '  align-items: flex-start;',
      '}',
      /* SOW header cell — gives the status bar room to breathe. Vertical
         alignment top so the bar starts at the same y-line as the bid
         columns badges. */
      'td.scw-bid-review__sow-header-cell {',
      '  vertical-align: top; padding: 8px 10px; min-width: 240px;',
      '  height: 1px;',  // collapse to content baseline so child height:100% works
      '}',
      /* SOW Name — editable text input pinned at the top of the SOW
         column header, above the proposal block + metrics. Stacks
         label-on-top so the input gets the full available width. */
      '.scw-bid-review__sow-name {',
      '  display: flex; flex-direction: column; gap: 3px;',
      '  margin-bottom: 8px;',
      '}',
      '.scw-bid-review__sow-name-label {',
      '  text-transform: uppercase; letter-spacing: 0.04em;',
      '  font: 700 10px/1 system-ui, sans-serif; color: #64748b;',
      '}',
      '.scw-bid-review__sow-name-input {',
      '  width: 100%; padding: 5px 8px;',
      '  border: 1px solid #cbd5e1; border-radius: 4px;',
      '  font: 700 14px/1.2 system-ui, sans-serif; color: #0f172a;',
      '  background: #fff;',
      '  text-align: center;',
      '}',
      '.scw-bid-review__sow-name-input:focus {',
      '  outline: none; border-color: #0d9488;',
      '  box-shadow: 0 0 0 2px rgba(13, 148, 136, 0.2);',
      '}',
      '.scw-bid-review__sow-name-input--saving { background: #fef3c7; }',
      '.scw-bid-review__sow-name-input--saved  { background: #ecfdf5; }',
      /* Survey Costs / Margin — stacked vertically (one per line). */
      '.scw-bid-review__sow-metrics {',
      '  display: flex; flex-direction: column; gap: 4px;',
      '  align-items: stretch;',
      '}',
      '.scw-bid-review__sow-metric {',
      '  display: flex; align-items: center; gap: 8px;',
      '  justify-content: space-between;',
      '  font: 600 12px/1.2 system-ui, sans-serif; color: #334155;',
      '}',
      '.scw-bid-review__sow-metric-label {',
      '  text-transform: uppercase; letter-spacing: 0.04em;',
      '  font-size: 10.5px; color: #64748b;',
      '}',
      '.scw-bid-review__sow-metric-value {',
      '  font-size: 13px; color: #0f172a;',
      '}',
      '.scw-bid-review__sow-metric-input {',
      '  width: 110px; padding: 4px 6px;',
      '  border: 1px solid #cbd5e1; border-radius: 4px;',
      '  font: 500 12px/1.2 system-ui, sans-serif; color: #0f172a;',
      '  background: #fff;',
      '  text-align: right;',
      '}',
      /* Drop the published-quote-info top divider when it lives in
         the bid-review SOW status bar. */
      '.scw-bid-review__sow-status .scw-pq-info--compact {',
      '  border-top: none !important;',
      '  margin-top: 0;',
      '  padding-top: 0;',
      '}',
      /* PDF icon now rides next to the quote name link. Hide the
         filename text leftover from published-quote-info\'s default
         render, keep just the icon. */
      '.scw-bid-review__sow-status .scw-pq-pdf {',
      '  display: inline-flex; align-items: center;',
      '  margin-left: 6px; vertical-align: middle;',
      '  color: #163C6E; opacity: 0.85;',
      '  font-size: 0;', /* hides any trailing text node */
      '}',
      '.scw-bid-review__sow-status .scw-pq-pdf:hover { opacity: 1; }',
      '.scw-bid-review__sow-metric-input:focus {',
      '  outline: none; border-color: #0d9488;',
      '  box-shadow: 0 0 0 2px rgba(13, 148, 136, 0.2);',
      '}',
      '.scw-bid-review__sow-metric-input--saving {',
      '  background: #fef3c7;',
      '}',
      '.scw-bid-review__sow-metric-input--saved {',
      '  background: #ecfdf5;',
      '}',
      /* Preview-Proposal pill inside the SOW status bar — restyled to
         match the .scw-bid-review__btn--adopt "Sync to SOW" button in
         the bid columns (same font / padding / border-radius / color). */
      '.scw-bid-review__sow-status .scw-ops-pill,',
      '.scw-bid-review__sow-status .scw-ops-pill:hover,',
      '.scw-bid-review__sow-status .scw-ops-pill:visited {',
      '  display: inline-flex; align-items: center; justify-content: center;',
      '  align-self: stretch; margin-top: auto;',  // bottom-align via flex auto-margin
      '  padding: 4px 8px;',
      '  border: none; border-radius: 4px;',
      '  font: 600 11px/1.2 system-ui, sans-serif;',
      '  background: #0891b2; color: #fff !important;',
      '  text-decoration: none; cursor: pointer;',
      '  white-space: nowrap; min-height: 0; gap: 4px;',
      '  transition: filter .15s;',
      '}',
      '.scw-bid-review__sow-status .scw-ops-pill:hover {',
      '  filter: brightness(0.92);',
      '}',
      /* Pending-state ("Processing X…") variant — keep the busy look so
         users still see the spinner instead of the action affordance. */
      '.scw-bid-review__sow-status .scw-ops-pill.is-pending {',
      '  background: #94a3b8; cursor: not-allowed;',
      '}',
      /* Hide the info-tooltip dot only when its data-scw-tip is empty —
         otherwise the auto-revert note dot would inherit the dark teal
         background and look out of place against the button. */
      '.scw-bid-review__sow-status .scw-ops-pill .scw-ops-info {',
      '  background: rgba(255,255,255,.2); color: #fff;',
      '}',
      /* DOC_files attached to this SOW or bid package (view_3926).
         Compact list with a small label, doc-type chip, file-icon
         link, and optional notes. Same shape in both the SOW status
         bar and bid column headers so the visual language matches. */
      '.scw-bid-review__docs {',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 3px;',
      '  margin-top: 6px;',
      '  padding-top: 6px;',
      '  border-top: 1px dashed #cbd5e1;',
      '}',
      '.scw-bid-review__docs-label {',
      '  font-size: 9.5px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.06em;',
      '  color: #64748b;',
      '}',
      '.scw-bid-review__docs-item {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 6px;',
      '  font-size: 11px;',
      '  color: #1e293b;',
      '}',
      '.scw-bid-review__docs-type {',
      '  display: inline-block;',
      '  flex: 0 0 auto;',
      '  padding: 1px 6px;',
      '  font-size: 10px;',
      '  font-weight: 600;',
      '  border-radius: 3px;',
      '  background: #e2e8f0;',
      '  color: #334155;',
      '}',
      '.scw-bid-review__docs-link {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  gap: 3px;',
      '  flex: 1 1 auto;',
      '  min-width: 0;',
      '  color: #295f91;',
      '  text-decoration: none;',
      '  white-space: nowrap;',
      '  overflow: hidden;',
      '  text-overflow: ellipsis;',
      '}',
      '.scw-bid-review__docs-link:hover {',
      '  text-decoration: underline;',
      '}',
      '.scw-bid-review__docs-link svg {',
      '  flex: 0 0 auto;',
      '  opacity: 0.7;',
      '}',
      '.scw-bid-review__docs-notes {',
      '  flex: 0 0 auto;',
      '  font-size: 10px;',
      '  color: #94a3b8;',
      '  font-style: italic;',
      '  max-width: 120px;',
      '  white-space: nowrap;',
      '  overflow: hidden;',
      '  text-overflow: ellipsis;',
      '}',

      /* "Add PM & Mobilization" button (lives inside the margin-low
         warning) — stretched to full width of the warning box. The
         ops-review-pill default sits left-aligned with max-content
         width; override both. */
      '.scw-bid-review__sow-status .scw-ops-margin-warning__btn,',
      '.scw-bid-review__sow-actions .scw-ops-margin-warning__btn {',
      '  flex: 0 0 100%; max-width: none; margin-left: 0; width: 100%;',
      '  justify-content: center; text-align: center;',
      '  white-space: normal;',
      '}',

      /* SOW action cell (r3) — bottom-aligned column of full-width
         buttons that visually mirror the bid-column .scw-bid-review__btn
         buttons (Sync to SOW etc.). Margin-warning, Preview Proposal
         pill, and any nested buttons stack vertically; the bottom of
         the stack aligns with the bottom of the cell so they line up
         horizontally with the bid-column action buttons. */
      '.scw-bid-review__sow-action-cell {',
      '  text-align: center;',
      '  vertical-align: bottom;',
      '}',
      '.scw-bid-review__sow-actions {',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 3px;',
      '  width: 100%;',
      '}',
      /* Stretch every direct child to full width. */
      '.scw-bid-review__sow-actions > * {',
      '  width: 100%;',
      '}',
      /* Preview Proposal pill — match .scw-bid-review__btn font/padding
         and force full width regardless of inline ops-pill styles. */
      '.scw-bid-review__sow-actions .scw-ops-pill,',
      '.scw-bid-review__sow-actions .scw-ops-pill:hover,',
      '.scw-bid-review__sow-actions .scw-ops-pill:visited {',
      '  display: flex; align-items: center; justify-content: center;',
      '  width: 100%;',
      '  padding: 4px 8px;',
      '  border: none; border-radius: 4px;',
      '  font: 600 11px/1.2 system-ui, sans-serif;',
      '  background: #0891b2; color: #fff !important;',
      '  text-decoration: none; cursor: pointer;',
      '  white-space: nowrap; min-height: 0; gap: 4px;',
      '  transition: filter .15s;',
      '  margin: 3px 0 0 0;',
      '}',
      '.scw-bid-review__sow-actions .scw-ops-pill:hover {',
      '  filter: brightness(0.92);',
      '}',
      '.scw-bid-review__sow-actions .scw-ops-pill.is-pending {',
      '  background: #94a3b8; cursor: not-allowed;',
      '}',
      '.scw-bid-review__sow-actions .scw-ops-pill .scw-ops-info {',
      '  background: rgba(255,255,255,.2); color: #fff;',
      '}',
      /* Margin-low warning block inside the actions cell — strip its
         outer padding so it aligns flush with the pill above/below. */
      '.scw-bid-review__sow-actions .scw-ops-margin-warning {',
      '  width: 100%;',
      '  margin: 0;',
      '}',
      /* Any nested btn inside the warning matches the bid-column btn
         font + padding. */
      '.scw-bid-review__sow-actions .scw-ops-margin-warning__btn,',
      '.scw-bid-review__sow-actions button {',
      '  font: 600 11px/1.2 system-ui, sans-serif;',
      '  padding: 4px 8px;',
      '  border-radius: 4px;',
      '}',

      /* ── table ─────────────────────────────────────────────── */
      '.scw-bid-review__table {',
      '  width: 100%;',
      '  border-collapse: collapse;',
      '  table-layout: fixed;',
      '  min-width: 700px;',
      '}',

      /* ── header row ────────────────────────────────────────── */
      '.scw-bid-review__header-row th {',
      '  position: sticky;',
      '  top: 0;',
      '  z-index: 2;',
      '  background: #f8fafc;',
      '  border-bottom: 2px solid #cbd5e1;',
      '  padding: 10px 8px;',
      '  text-align: left;',
      '  vertical-align: top;',
      '  font-weight: 600;',
      '  font-size: 13px;',
      '}',

      '.scw-bid-review__sow-header {',
      '  width: 100px;',
      '  min-width: 80px;',
      '  text-align: center;',
      '}',

      /* SOW detail, bid columns, and change request column share equal width */
      '.scw-bid-review__sow-detail-header,',
      '.scw-bid-review__pkg-header,',
      '.scw-bid-review__actions-header {',
      '}',

      /* When a SOW has no pending CRs, no noBid/surveyNoBid rows, and
         no header submit buttons, the .cr-col cells are physically
         removed from the DOM by buildSowSection — see the comment
         there. The .scw-bid-review__table--no-cr class is left on the
         table as a hook for any other code that wants to reason
         about the collapsed-column state. */
      '.scw-bid-review__header-titles th.scw-bid-review__sow-detail-header {',
      '  text-align: center !important;',
      '  font-size: 12px !important;',
      '}',
      '.scw-bid-review__header-details .scw-bid-review__header-detail-cell {',
      '  text-align: center;',
      '  padding-top: 10px;',
      '}',

      /* ── unified column header (3-row layout) ─────────── */
      '.scw-bid-review__header-row th,',
      '.scw-bid-review__header-row td {',
      '  text-align: center;',
      '  vertical-align: middle;',
      '  padding: 4px 8px;',
      '}',
      '.scw-bid-review__header-titles th {',
      '  font-size: 12px !important;',
      '  font-weight: 700 !important;',
      '  text-transform: uppercase !important;',
      '  letter-spacing: .05em !important;',
      '  text-align: center !important;',
      '  color: #334155;',
      '  padding-top: 10px;',
      '  border-bottom: none;',
      '}',
      '.scw-bid-review__col-title-total {',
      '  font-size: 11px !important;',
      '  font-weight: 500 !important;',
      '  text-transform: none !important;',
      '  letter-spacing: 0 !important;',
      '  color: #64748b;',
      '  margin-top: 2px;',
      '}',
      '.scw-bid-review__col-title-total-label {',
      '  color: #94a3b8;',
      '}',
      '.scw-bid-review__col-title-total-value {',
      '  color: #334155;',
      '  font-weight: 600 !important;',
      '}',
      '.scw-bid-review__header-details td {',
      '  font-size: 11px;',
      '  color: #64748b;',
      '  border-bottom: none;',
      '  padding-top: 0;',
      '}',
      '.scw-bid-review__header-actions td {',
      '  padding-top: 14px;',     /* breathing room above the action stack */
      '  padding-bottom: 8px;',
      '}',
      '.scw-bid-review__header-detail-cell {',
      '  text-align: center;',
      '}',
      '.scw-bid-review__header-action-cell {',
      '  text-align: center;',
      '  vertical-align: bottom;',
      '}',
      '.scw-bid-review__header-action-cell .scw-bid-review__btn {',
      '  display: block;',
      '  width: 100%;',
      '  margin: 3px 0;',
      '}',
      /* Bid-column header detail cell sits above the actions cell —
         pin the badge + bid-name to the top so the actions stay
         flush at the bottom regardless of how tall the SOW status
         column makes the row. */
      '.scw-bid-review__header-details .scw-bid-review__header-detail-cell:not(.scw-bid-review__sow-header-cell) {',
      '  vertical-align: top;',
      '}',
      '.scw-bid-review__col-status {',
      '  font-size: 10px;',
      '  line-height: 1;',
      '  margin-bottom: 2px;',
      '}',
      '.scw-bid-review__col-title {',
      '  font-size: 11px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: .05em;',
      '  color: #334155;',
      '}',
      '.scw-bid-review__col-subtitle {',
      '  font-size: 11px;',
      '  font-weight: 500;',
      '  color: #64748b;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  gap: 4px;',
      '  margin-top: 1px;',
      '}',
      '.scw-bid-review__col-links {',
      '  display: flex;',
      '  flex-direction: column;',
      '  align-items: center;',
      '  gap: 2px;',
      '  margin-top: 4px;',
      '}',
      '.scw-bid-review__col-buttons {',
      '  display: flex;',
      '  flex-direction: column;',
      '  align-items: center;',
      '  gap: 3px;',
      '  margin-top: 6px;',
      '}',

      /* ── package column header ─────────────────────────────── */

      '.scw-bid-review__pkg-name {',
      '  font-size: 14px;',
      '  font-weight: 700;',
      '  color: #0f172a;',
      '  margin-bottom: 4px;',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 6px;',
      '}',

      '.scw-bid-review__pdf-link {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  color: #dc2626;',
      '  opacity: .7;',
      '  transition: opacity 150ms ease;',
      '  flex-shrink: 0;',
      '}',
      '.scw-bid-review__pdf-link:hover { opacity: 1; }',
      '.scw-bid-review__pdf-link svg { display: block; width: 20px; height: 20px; }',

      '.scw-bid-review__cr-link {',
      '  display: block;',
      '  font-size: 11px;',
      '  font-weight: 600;',
      '  color: #dc6900;',
      '  margin-top: 4px;',
      '  text-decoration: none;',
      '}',
      '.scw-bid-review__cr-link:hover {',
      '  text-decoration: underline;',
      '  color: #b85700;',
      '}',

      '.scw-bid-review__pkg-counts {',
      '  font-size: 11px;',
      '  font-weight: 400;',
      '  color: #64748b;',
      '  margin-bottom: 6px;',
      '}',

      '.scw-bid-review__pkg-actions {',
      '  display: flex;',
      '  flex-direction: row;',
      '  gap: 4px;',
      '  margin-top: 4px;',
      '}',

      /* ── buttons ───────────────────────────────────────────── */
      '.scw-bid-review__btn {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  padding: 4px 8px;',
      '  border: none;',
      '  border-radius: 4px;',
      '  font: 600 11px/1.2 system-ui, sans-serif;',
      '  cursor: pointer;',
      '  transition: opacity .15s, filter .15s;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-review__btn:hover {',
      '  filter: brightness(0.92);',
      '}',

      '.scw-bid-review__btn--adopt {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--create {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--combo {',
      '  background: #7c3aed;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--skip {',
      '  background: #e2e8f0;',
      '  color: #475569;',
      '}',

      '.scw-bid-review__btn--revision {',
      '  background: #fbbf24;',
      '  color: #78350f;',
      '}',

      '.scw-bid-review__btn--change-req {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--change-edit {',
      '  background: #f59e0b;',
      '  color: #78350f;',
      '}',

      '.scw-bid-review__btn--remove-bid {',
      '  background: #fef2f2;',
      '  color: #dc2626;',
      '  border: 1px solid #fca5a5;',
      '}',

      '.scw-bid-review__toolbar {',
      '  display: flex;',
      '  justify-content: flex-end;',
      '  gap: 8px;',
      '  padding: 8px 4px;',
      '  margin-bottom: 4px;',
      '}',

      '.scw-bid-review__btn--create-sow {',
      '  background: #07467c;',
      '  color: #fff;',
      '  font-size: 13px;',
      '  padding: 8px 14px;',
      '}',

      '.scw-bid-review__btn--busy {',
      '  opacity: 0.5;',
      '  pointer-events: none;',
      '  cursor: default;',
      '}',

      '.scw-bid-review__btn--sm {',
      '  font-size: 10px;',
      '  padding: 3px 6px;',
      '}',

      /* ── collapsible group headers (accordion style) ────────── */
      '.scw-bid-review__group-header {',
      '  cursor: pointer;',
      '  user-select: none;',
      '  -webkit-user-select: none;',
      '}',

      '.scw-bid-review__group-header td {',
      '  position: relative;',
      '  background: #f1f5f9;',
      '  padding: 0;',
      '  font-weight: 700;',
      '  font-size: 13px;',
      '  color: #334155;',
      '  border-bottom: 1px solid #cbd5e1;',
      '  border-left: 4px solid #295f91;',
      '}',

      '.scw-bid-review__grp-inner {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 8px;',
      '  padding: 10px 12px 10px 12px;',
      '}',

      '.scw-bid-review__group-header:hover td {',
      '  background: #e8edf3;',
      '}',

      /* Chevron in group header */
      '.scw-bid-review__grp-chevron {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  flex: 0 0 auto;',
      '  color: #295f91;',
      '  transition: transform 220ms ease;',
      '}',

      '.scw-bid-review__group-header--collapsed .scw-bid-review__grp-chevron {',
      '  transform: rotate(-90deg);',
      '}',

      /* Title */
      '.scw-bid-review__grp-title {',
      '  flex: 1 1 auto;',
      '}',

      /* Count pill — mirrors KTL accordion count */
      '.scw-bid-review__grp-count {',
      '  display: inline-block;',
      '  padding: 2px 8px;',
      '  font-size: 11px;',
      '  font-weight: 600;',
      '  line-height: 1.4;',
      '  border-radius: 999px;',
      '  background: rgba(41, 95, 145, 0.12);',
      '  border: 1px solid rgba(41, 95, 145, 0.22);',
      '  color: #295f91;',
      '}',

      /* Auto-mounted detail row beneath an L1 group header — shows
         photos (field_771) + Survey Notes (field_2457) + SCW Notes
         (field_1643) for the matching MDF/IDF record in view_3822.
         The row is built only when at least one of those fields has
         data. The accordion toggle on the L1 header walks siblings
         and hides this row along with the rest of the group. */
      '.scw-bid-review__l1-detail-row > td {',
      '  background: #f8fafc;',
      '  border-bottom: 1px solid #cbd5e1;',
      '  padding: 0;',
      '}',
      '.scw-bid-review__l1-detail-wrap {',
      '  padding: 14px 18px;',
      '  display: flex;',
      '  flex-wrap: wrap;',
      '  gap: 18px;',
      '  align-items: flex-start;',
      '}',
      '.scw-bid-review__l1-detail-section {',
      '  flex: 1 1 280px;',
      '  min-width: 0;',
      '}',
      '.scw-bid-review__l1-detail-label {',
      '  font-size: 10px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.06em;',
      '  color: #64748b;',
      '  margin-bottom: 6px;',
      '}',
      '.scw-bid-review__l1-detail-text {',
      '  font-size: 12px;',
      '  line-height: 1.5;',
      '  color: #1e293b;',
      '  white-space: pre-wrap;',
      '  word-break: break-word;',
      '}',
      '.scw-bid-review__l1-detail-empty {',
      '  font-size: 12px;',
      '  color: #94a3b8;',
      '  font-style: italic;',
      '}',
      /* Photo strip — matches the natural-width / capped-height
         look-and-feel of the inline-photo-row strip used on device
         worksheets (see inline-photo-row.js). Photos render at their
         natural aspect ratio with a 200px height cap, wrap onto
         multiple lines, and click through to the full-size image
         in a new tab. */
      '.scw-bid-review__l1-detail-photos {',
      '  display: flex;',
      '  flex-wrap: wrap;',
      '  gap: 8px;',
      '}',
      '.scw-bid-review__l1-detail-photo {',
      '  display: block;',
      '  flex: 0 0 auto;',
      '  border-radius: 6px;',
      '  border: 1px solid #ddd;',
      '  background: #fff;',
      '  box-shadow: 0 1px 4px rgba(0,0,0,.08);',
      '  transition: transform 120ms ease, box-shadow 120ms ease;',
      '  overflow: hidden;',
      '}',
      '.scw-bid-review__l1-detail-photo:hover {',
      '  transform: scale(1.03);',
      '  box-shadow: 0 3px 12px rgba(0,0,0,.15);',
      '}',
      /* Override Knack default ".kn-content img { max-width: 100% }". */
      '.scw-bid-review__l1-detail-photo img,',
      '.kn-content .scw-bid-review__l1-detail-photo img {',
      '  display: block;',
      '  width: auto;',
      '  height: 200px;',
      '  max-width: none;',
      '}',

      /* ── L1 survey-notes callout row ──────────────────────
         Promoted out of the general L1 detail wrap so the most
         actionable thing the surveyor leaves behind reads with
         weight. Amber palette matches the revision-badge family
         (same #fef3c7 / #92400e tokens) so "things you should
         actually look at" stay visually consistent across the app.
         !important on bg/border to win over Knack's default
         tbody>tr>td styling (matching specificity, but Knack's
         stylesheet sometimes loads after ours). */
      '.scw-bid-review__l1-survey-notes-row > td {',
      '  background: #fffbeb !important;',
      '  border-bottom: 1px solid #fde68a !important;',
      '  border-left: 4px solid #f59e0b !important;',
      '  padding: 0 !important;',
      '}',
      '.scw-bid-review__l1-survey-notes-wrap {',
      '  display: flex;',
      '  align-items: flex-start;',
      '  gap: 10px;',
      '  padding: 12px 16px 12px 14px;',
      '}',
      '.scw-bid-review__l1-survey-notes-icon {',
      '  flex: 0 0 auto;',
      '  display: inline-flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  color: #b45309;',
      '  margin-top: 1px;',
      '}',
      '.scw-bid-review__l1-survey-notes-body {',
      '  flex: 1 1 auto;',
      '  min-width: 0;',
      '}',
      '.scw-bid-review__l1-survey-notes-label {',
      '  font-size: 10px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.06em;',
      '  color: #92400e;',
      '  margin-bottom: 3px;',
      '}',
      '.scw-bid-review__l1-survey-notes-text {',
      '  font-size: 14px;',
      '  line-height: 1.5;',
      '  color: #78350f;',
      '  white-space: pre-wrap;',
      '  word-break: break-word;',
      '}',

      /* ── Dedicated Photos column ─────────────────────────────
         A column between Line Item and SOW Detail. Shows one large
         thumb (~200px square) per row so reviewers can recognise the
         shot at a glance. Surplus shown as "+N" pill. The column is
         scraped from view_3921 and cached across re-renders to avoid
         the brief disappearance when view_3921 rebuilds.

         Clicking a thumb opens the row's expand panel WITH a
         side-by-side photo viewer (see init.js openWithPhoto +
         .scw-bid-review__photo-viewer below). */
      '.scw-bid-review__photos-header {',
      '  width: 208px;',
      '  min-width: 208px;',
      '  text-align: center;',
      '  font-size: 12px;',
      '}',
      '.scw-bid-review__photos-cell {',
      '  width: 208px;',
      '  min-width: 208px;',
      '  padding: 6px 4px !important;',
      '  vertical-align: top;',
      '}',
      '.scw-bid-review__photos-stack {',
      '  display: flex;',
      '  flex-direction: column;',
      '  align-items: center;',
      '  gap: 4px;',
      '}',
      '.scw-bid-review__photos-thumb {',
      '  display: block;',
      '  width: 200px;',
      '  height: 200px;',
      '  border-radius: 6px;',
      '  border: 1px solid #cbd5e1;',
      '  background: #fff;',
      '  overflow: hidden;',
      '  transition: transform 100ms ease, box-shadow 100ms ease;',
      '  position: relative;',
      '  cursor: zoom-in;',
      '}',
      '.scw-bid-review__photos-thumb:hover {',
      '  transform: scale(1.02);',
      '  box-shadow: 0 4px 14px rgba(0,0,0,.22);',
      '  z-index: 2;',
      '}',
      /* Override Knack default ".kn-content img { max-width: 100% }" */
      '.scw-bid-review__photos-thumb img,',
      '.kn-content .scw-bid-review__photos-thumb img {',
      '  display: block;',
      '  width: 100%;',
      '  height: 100%;',
      '  object-fit: cover;',
      '  max-width: none;',
      '}',
      '.scw-bid-review__photos-more {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  min-width: 32px;',
      '  height: 22px;',
      '  padding: 0 8px;',
      '  border-radius: 11px;',
      '  background: #475569;',
      '  color: #fff;',
      '  font-size: 11px;',
      '  font-weight: 700;',
      '  margin-top: 2px;',
      '  cursor: pointer;',
      '}',
      '.scw-bid-review__photos-empty {',
      '  font-size: 11px;',
      '  color: #cbd5e1;',
      '  text-align: center;',
      '  padding: 10px 4px;',
      '}',

      /* ── Inline + Add to bid pill (data cell, noBid rows) ───
         Surfaced in the data cell next to NOT ON BID / NOT
         SURVEYED badges so the Sub Bid Revisions column can hide
         when no CRs are pending submission. */
      '.scw-bid-review__inline-add-btn {',
      '  display: inline-block;',
      '  margin-top: 6px;',
      '  padding: 4px 10px;',
      '  border-radius: 4px;',
      '  border: 1px solid #16a34a;',
      '  background: #fff;',
      '  color: #16a34a;',
      '  font-size: 11px;',
      '  font-weight: 600;',
      '  cursor: pointer;',
      '  line-height: 1.2;',
      '}',
      '.scw-bid-review__inline-add-btn:hover {',
      '  background: #16a34a;',
      '  color: #fff;',
      '}',
      '.scw-bid-review__inline-add-btn:disabled {',
      '  border-color: #cbd5e1;',
      '  color: #94a3b8;',
      '  cursor: not-allowed;',
      '}',

      /* ── subgroup headers (proposalBucket within mdfIdf) ──── */
      '.scw-bid-review__subgroup-header td {',
      '  background: #f8fafc;',
      '  padding: 0;',
      '  border-bottom: 1px solid #e2e8f0;',
      '}',

      '.scw-bid-review__subgrp-inner {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 6px;',
      '  padding: 6px 12px 6px 28px;',
      '}',

      '.scw-bid-review__subgrp-title {',
      '  font-size: 12px;',
      '  font-weight: 600;',
      '  color: #475569;',
      '}',

      '.scw-bid-review__subgrp-count {',
      '  display: inline-block;',
      '  padding: 1px 6px;',
      '  font-size: 10px;',
      '  font-weight: 600;',
      '  line-height: 1.4;',
      '  border-radius: 999px;',
      '  background: #f1f5f9;',
      '  color: #64748b;',
      '}',

      /* ── data rows ─────────────────────────────────────────── */
      '.scw-bid-review__row td {',
      '  padding: 6px 8px;',
      '  border-bottom: 1px solid #e5e7eb;',
      '  vertical-align: top;',
      '}',

      '.scw-bid-review__row:nth-child(even) td {',
      '  background: #fafbfc;',
      '}',

      '.scw-bid-review__row:hover td {',
      '  background: #eff6ff;',
      '}',

      /* Click-to-expand row: cursor + a soft blue drop-shadow halo on
         the SOW columns (cells 1+2) that visually continues the panel\'s
         shadow above the row, so the data row + panel read as one unit. */
      '.scw-bid-review__row--expandable { cursor: pointer; }',
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(1),',
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(2) {',
      '  position: relative;',
      '  background: #fff !important;',
      '}',
      /* When the row is expanded the worksheet card below is the
         source of truth for these fields — hide every duplicated
         detail in the SOW cell except the product label so the user
         doesn\'t see two stale-vs-fresh copies. */
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td.scw-bid-review__sow-detail > *:not(.scw-bid-review__cell-label) {',
      '  display: none !important;',
      '}',
      /* Top halo + outer side shadows. Side shadows match ws-card\'s
         left/right shadows but bumped 20% (0.315 → 0.378) so the left
         glow has a bit more presence than the panel\'s. */
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(1) {',
      '  box-shadow: 0 -18px 22px -10px rgba(2, 132, 199, 0.46),',
      '              -10px 14px 18px -10px rgba(2, 132, 199, 0.378);',
      '}',
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(2) {',
      '  box-shadow: 0 -18px 22px -10px rgba(2, 132, 199, 0.46),',
      '              10px 14px 18px -10px rgba(2, 132, 199, 0.378);',
      '}',

      /* Expand-row: hidden until the parent row is open. The injected
         worksheet card renders inside a mini-table so device-worksheet\'s
         <tr.scw-ws-row> structure stays valid. */
      '.scw-bid-review__expand-row { display: none; }',
      '.scw-bid-review__expand-row--open { display: table-row; }',
      '.scw-bid-review__expand-cell {',
      '  padding: 0 0 12px !important;',
      '  background: transparent;',
      '  border: none !important;',
      '}',
      /* Push the panel up to overlap with the data row above; square top
         corners + rounded bottom so it reads as integrated. Drop the
         worksheet card\'s default 1px border — the blue shadow alone
         frames the panel. */
      '.scw-bid-review__expand-cell .scw-ws-card {',
      '  margin-top: -5px;',
      '  border-radius: 0 0 8px 8px !important;',
      '  border: none !important;',
      '}',
      /* Sink the bid + actions cells of the expanded data row so the
         lifted panel above casts an inset shadow into them. */
      '.scw-bid-review__row--expandable[aria-expanded="true"] > td:nth-child(n+3) {',
      '  box-shadow: inset 0 -8px 10px -6px rgba(2, 132, 199, 0.45);',
      '}',
      '.scw-bid-review__expand-table {',
      '  width: 100%;',
      '  border-collapse: collapse;',
      '  background: #fff;',
      '}',
      /* Tint the worksheet card\'s expanded drop shadow blue (overrides
         device-worksheet\'s default black/gray shadow). Big positive
         y-offset combined with negative spread keeps the shadow strictly
         below + to the sides — never on top. */
      '.scw-bid-review__expand-cell .scw-ws-card:has(.scw-ws-open),',
      '.scw-bid-review__expand-cell .scw-ws-card {',
      '  box-shadow: 0 16px 20px -10px rgba(2, 132, 199, 0.385),',
      '              -10px 14px 18px -10px rgba(2, 132, 199, 0.315),',
      '              10px 14px 18px -10px rgba(2, 132, 199, 0.315) !important;',
      '}',
      '.scw-bid-review__expand-table > tbody > tr > td {',
      '  padding: 0 !important;',
      '  border: none !important;',
      '}',
      '.scw-bid-review__expand-loading {',
      '  padding: 16px; color: #64748b; font-size: 13px; text-align: center;',
      '}',

      /* ── Three-column expand panel ────────────────────────────
         When the user opens a row, the original <tr> is hidden (rule
         below) and the expand-row holds a 3-column panel:
           [photo viewer] [worksheet card] [bid details]
         The td stays a normal table-cell — flex layout is on a child
         div so the cell still spans the full row width. */
      '.scw-bid-review__expand-cell { padding: 12px 12px !important; background: #f8fafc; }',
      '.scw-bid-review__panel {',
      '  background: #fff;',
      '  border-radius: 8px;',
      '  box-shadow: 0 8px 24px -8px rgba(2, 132, 199, 0.35);',
      '  border: 1px solid #cbd5e1;',
      '  overflow: hidden;',
      '}',
      '.scw-bid-review__panel-header {',
      '  display: flex; align-items: center; gap: 12px;',
      '  padding: 10px 14px;',
      '  background: #295F91;',
      '  color: #fff;',
      '}',
      '.scw-bid-review__panel-title {',
      '  flex: 1; min-width: 0;',
      '  font: 600 13px/1.3 system-ui, -apple-system, Segoe UI, sans-serif;',
      '  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
      '}',
      '.scw-bid-review__panel-close {',
      '  flex: 0 0 auto;',
      '  background: rgba(255,255,255,0.18);',
      '  color: #fff;',
      '  border: 1px solid rgba(255,255,255,0.28);',
      '  border-radius: 6px;',
      '  width: 28px; height: 28px;',
      '  font: 600 16px/1 system-ui, sans-serif;',
      '  cursor: pointer;',
      '  display: inline-flex; align-items: center; justify-content: center;',
      '}',
      '.scw-bid-review__panel-close:hover { background: rgba(255,255,255,0.32); }',

      '.scw-bid-review__panel-cols {',
      '  display: flex;',
      '  align-items: stretch;',
      '  gap: 0;',
      '  width: 100%;',
      '}',
      '.scw-bid-review__panel-col { min-width: 0; }',
      '.scw-bid-review__panel-col--photo {',
      '  flex: 0 0 0;',
      '  width: 0;',
      '  overflow: hidden;',
      '  transition: flex-basis 200ms ease, width 200ms ease;',
      '}',
      '.scw-bid-review__panel-col--photo-active {',
      '  flex: 0 0 38%;',
      '  width: auto;',
      '  max-width: 520px;',
      '  border-right: 1px solid #e2e8f0;',
      '}',
      '.scw-bid-review__panel-col--worksheet {',
      '  flex: 1 1 auto;',
      '  padding: 4px 0;',
      '}',
      '.scw-bid-review__panel-col--bid {',
      '  flex: 0 0 280px;',
      '  border-left: 1px solid #e2e8f0;',
      '  background: #f8fafc;',
      '  padding: 10px;',
      '  display: flex; flex-direction: column; gap: 10px;',
      '}',

      /* Hide the original data row while expanded — the panel takes
         its place. Group headers / detail rows above and below
         continue to render normally. */
      '.scw-bid-review__row--expandable[aria-expanded="true"] { display: none; }',

      /* Bid detail cards in the right column (cloned per-package cells
         + actions cell from the data row). Stack vertically. */
      '.scw-bid-review__bid-card {',
      '  background: #fff;',
      '  border: 1px solid #e2e8f0;',
      '  border-radius: 6px;',
      '  padding: 8px 10px;',
      '}',
      '.scw-bid-review__bid-card-label {',
      '  font: 600 10px/1 system-ui, sans-serif;',
      '  letter-spacing: .04em;',
      '  text-transform: uppercase;',
      '  color: #64748b;',
      '  margin-bottom: 6px;',
      '}',
      '.scw-bid-review__bid-card-body { font-size: 12px; color: #1e293b; }',
      '.scw-bid-review__bid-card-body > * { max-width: 100%; }',

      /* Worksheet card overrides — only when mounted inside the
         expand panel: single-column section grid, photos field row
         hidden (the photo viewer column handles that), drop the
         negative-margin lift + extra box-shadow that were tuned for
         the old "row + panel below" layout. */
      '.scw-bid-review__panel-col--worksheet .scw-ws-sections {',
      '  grid-template-columns: 1fr !important;',
      '}',
      '.scw-bid-review__panel-col--worksheet tr:has(td[data-field-key="field_771"]) {',
      '  display: none !important;',
      '}',
      '.scw-bid-review__panel-col--worksheet .scw-ws-card {',
      '  margin-top: 0 !important;',
      '  border-radius: 0 !important;',
      '  box-shadow: none !important;',
      '  border: none !important;',
      '}',
      /* The photo-viewer in the new layout sits inside the photo
         column, full-height, no detached blue glow. */
      '.scw-bid-review__panel-col--photo .scw-bid-review__photo-viewer {',
      '  margin-top: 0;',
      '  border-radius: 0;',
      '  box-shadow: none;',
      '  height: 100%;',
      '}',

      /* Legacy class kept for backwards compat with any straggling
         CSS overrides; new layout uses .scw-bid-review__panel-cols. */
      '.scw-bid-review__expand-flex {',
      '  display: flex;',
      '  align-items: stretch;',
      '  gap: 10px;',
      '  width: 100%;',
      '}',
      '.scw-bid-review__expand-flex > .scw-bid-review__expand-table {',
      '  flex: 1 1 0;',
      '  min-width: 0;',
      '}',
      '.scw-bid-review__photo-viewer {',
      '  flex: 0 0 42%;',
      '  max-width: 560px;',
      '  display: flex;',
      '  flex-direction: column;',
      '  background: #0f172a;',
      '  border-radius: 0 0 8px 8px;',
      '  margin-top: -5px;',
      '  overflow: hidden;',
      '  position: relative;',
      '  box-shadow: 0 16px 20px -10px rgba(2, 132, 199, 0.385),',
      '              -10px 14px 18px -10px rgba(2, 132, 199, 0.315),',
      '              10px 14px 18px -10px rgba(2, 132, 199, 0.315);',
      '}',
      '.scw-bid-review__photo-viewer-stage {',
      '  flex: 1 1 auto;',
      '  min-height: 320px;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  overflow: hidden;',
      '  position: relative;',
      '  cursor: zoom-out;',
      '}',
      '.scw-bid-review__photo-viewer-stage::after {',
      '  content: "Click to close";',
      '  position: absolute;',
      '  bottom: 8px; left: 50%;',
      '  transform: translateX(-50%);',
      '  padding: 3px 10px;',
      '  border-radius: 11px;',
      '  background: rgba(15, 23, 42, 0.65);',
      '  color: #fff;',
      '  font: 600 11px/1 system-ui, sans-serif;',
      '  opacity: 0;',
      '  pointer-events: none;',
      '  transition: opacity 120ms ease;',
      '}',
      '.scw-bid-review__photo-viewer-stage:hover::after { opacity: 1; }',
      '.scw-bid-review__photo-viewer-stage img,',
      '.kn-content .scw-bid-review__photo-viewer-stage img {',
      '  display: block;',
      '  max-width: 100%;',
      '  max-height: 100%;',
      '  width: auto;',
      '  height: auto;',
      '  object-fit: contain;',
      '}',
      '.scw-bid-review__photo-viewer-close {',
      '  position: absolute;',
      '  top: 8px; right: 8px;',
      '  width: 28px; height: 28px;',
      '  border-radius: 50%;',
      '  background: rgba(15, 23, 42, 0.75);',
      '  color: #fff;',
      '  border: 1px solid rgba(255,255,255,.25);',
      '  cursor: pointer;',
      '  font-size: 16px; line-height: 1;',
      '  display: inline-flex; align-items: center; justify-content: center;',
      '  z-index: 2;',
      '}',
      '.scw-bid-review__photo-viewer-close:hover { background: rgba(15, 23, 42, 0.95); }',
      '.scw-bid-review__photo-viewer-open {',
      '  position: absolute;',
      '  top: 8px; left: 8px;',
      '  padding: 4px 10px;',
      '  border-radius: 4px;',
      '  background: rgba(15, 23, 42, 0.75);',
      '  color: #fff;',
      '  border: 1px solid rgba(255,255,255,.25);',
      '  cursor: pointer;',
      '  font: 600 11px/1 system-ui, sans-serif;',
      '  text-decoration: none;',
      '  display: inline-flex; align-items: center; gap: 4px;',
      '  z-index: 2;',
      '}',
      '.scw-bid-review__photo-viewer-open:hover { background: rgba(15, 23, 42, 0.95); color: #fff; }',
      '.scw-bid-review__photo-viewer-strip {',
      '  flex: 0 0 auto;',
      '  display: flex;',
      '  gap: 4px;',
      '  padding: 6px 8px;',
      '  background: rgba(15, 23, 42, 0.95);',
      '  overflow-x: auto;',
      '}',
      '.scw-bid-review__photo-viewer-thumb {',
      '  flex: 0 0 auto;',
      '  width: 56px; height: 56px;',
      '  border-radius: 4px;',
      '  border: 2px solid transparent;',
      '  overflow: hidden;',
      '  cursor: pointer;',
      '  background: #1e293b;',
      '  padding: 0;',
      '}',
      '.scw-bid-review__photo-viewer-thumb img,',
      '.kn-content .scw-bid-review__photo-viewer-thumb img {',
      '  display: block;',
      '  width: 100%; height: 100%;',
      '  object-fit: cover;',
      '  max-width: none;',
      '}',
      '.scw-bid-review__photo-viewer-thumb--active {',
      '  border-color: #38bdf8;',
      '}',

      /* view_3921 (SOW line items) is shown alongside the bid review
         grid for diagnostic / inspection purposes. The grid still
         expands rows by moving worksheet cards out of view_3921, so
         leaving the source view visible can briefly show empty cells
         while a card is on loan. */

      /* ── SOW cell ──────────────────────────────────────────── */
      '.scw-bid-review__sow-cell {',
      '  font-weight: 600;',
      '  color: #1e293b;',
      '}',

      '.scw-bid-review__sow-cell--new {',
      '  font-weight: 600;',
      '  color: #1e293b;',
      '}',

      /* Row label (E-001 etc.) — block-level so the totals stack
         beneath it cleanly. */
      '.scw-bid-review__row-label {',
      '  font-weight: 600; color: #1e293b;',
      '}',

      /* Per-row Equipment + Install fee totals stacked under the
         row label. Each total = bold label on one line, $ value on
         the next. */
      '.scw-bid-review__row-totals {',
      '  display: flex; flex-direction: column; gap: 6px;',
      '  margin-top: 6px;',
      '}',
      '.scw-bid-review__row-total {',
      '  display: flex; flex-direction: column; gap: 0;',
      '  font: 500 11px/1.25 system-ui, sans-serif;',
      '  color: #64748b;',
      '}',
      '.scw-bid-review__row-total-label {',
      '  font-weight: 700;',
      '  color: #1e293b;',
      '}',
      '.scw-bid-review__row-total-value {',
      '  font-variant-numeric: tabular-nums;',
      '  color: #1e293b;',
      '}',

      '.scw-bid-review__new-badge {',
      '  display: inline-block;',
      '  padding: 1px 5px;',
      '  border-radius: 3px;',
      '  background: #2563eb;',
      '  color: #fff;',
      '  font-size: 9px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.5px;',
      '  vertical-align: middle;',
      '  margin-right: 4px;',
      '}',

      /* ── NO BID badge & row ──────────────────────────────────── */
      '.scw-bid-review__no-bid-badge {',
      '  display: inline-block;',
      '  padding: 1px 5px;',
      '  border-radius: 3px;',
      '  background: #dc2626;',
      '  color: #fff;',
      '  font-size: 9px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.5px;',
      '  vertical-align: middle;',
      '  margin-right: 4px;',
      '}',

      '.scw-bid-review__row--no-bid td {',
      '  background: #fef2f2 !important;',
      '}',

      '.scw-bid-review__row--no-bid:hover td {',
      '  background: #fee2e2 !important;',
      '}',

      /* ── SURVEY NO BID badge & row (on survey, not on any bid package) */
      '.scw-bid-review__survey-no-bid-badge {',
      '  display: inline-block;',
      '  padding: 1px 5px;',
      '  border-radius: 3px;',
      '  background: #d97706;',
      '  color: #fff;',
      '  font-size: 9px;',
      '  font-weight: 700;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.5px;',
      '  vertical-align: middle;',
      '  margin-right: 4px;',
      '}',

      '.scw-bid-review__row--survey-no-bid td {',
      '  background: #fffbeb !important;',
      '}',

      '.scw-bid-review__row--survey-no-bid:hover td {',
      '  background: #fef3c7 !important;',
      '}',

      /* ── package data cell ─────────────────────────────────── */
      '.scw-bid-review__cell-label {',
      '  font-size: 12px;',
      '  color: #334155;',
      '  margin-bottom: 2px;',
      '}',

      '.scw-bid-review__cell-values {',
      '  display: flex;',
      '  gap: 8px;',
      '  font-size: 12px;',
      '  color: #475569;',
      '}',

      '.scw-bid-review__cell-value {',
      '  font-weight: 600;',
      '  color: #0f172a;',
      '}',

      '.scw-bid-review__cell--missing {',
      '  color: #cbd5e1;',
      '  font-style: italic;',
      '  font-size: 12px;',
      '}',

      /* ── mismatch highlight (SOW vs Bid field pair differs) ── */
      '.scw-bid-review__cell--mismatch {',
      '  background: #fff7ed !important;',
      '  border-left: 3px solid #fb923c;',
      '}',

      /* ── per-field diff highlight (pinpoints WHICH values differ) ── */
      '.scw-bid-review__field-diff {',
      '  background: #fed7aa;',
      '  border-radius: 2px;',
      '  padding: 1px 4px;',
      '  box-decoration-break: clone;',
      '  -webkit-box-decoration-break: clone;',
      '}',

      '.scw-bid-review__cell-qty {',
      '  font-size: 11px;',
      '  color: #475569;',
      '  margin-top: 1px;',
      '}',

      '.scw-bid-review__cell-labor-desc {',
      '  font-size: 11px;',
      '  color: #475569;',
      '  margin-top: 1px;',
      '}',

      '.scw-bid-review__field-label {',
      '  font-weight: 600;',
      '  color: #64748b;',
      '}',

      '.scw-bid-review__cell-notes-divider {',
      '  border: none;',
      '  border-top: 1px solid #e2e8f0;',
      '  margin: 4px 0 2px;',
      '}',

      '.scw-bid-review__cell-notes {',
      '  font-size: 11px;',
      '  color: #64748b;',
      '  margin-top: 2px;',
      '}',

      '.scw-bid-review__cell-conn-device {',
      '  font-size: 11px;',
      '  color: #6366f1;',
      '  margin-top: 2px;',
      '  font-weight: 500;',
      '}',

      /* ── SOW detail cell ─────────────────────────────────────── */
      '.scw-bid-review__sow-detail {',
      '  vertical-align: top;',
      '  font-size: 12px;',
      '  position: relative;',
      '  padding-right: 200px;', /* room for the top-right Revise + Disconnect stack — must clear the widest button ("Revise bid to match →") */
      '}',
      /* Bid package data cells share the same top-right action zone.
         Drop :not(:last-child) — when the Sub Bid Revisions column is
         physically removed (no pending CRs / Add buttons), the last bid
         td becomes the row\'s last child and would lose position:
         relative, sending its absolute Revise/Remove buttons up to the
         document body. */
      '.scw-bid-review__row > td:nth-child(n+3) {',
      '  position: relative;',
      '  padding-right: 100px;', /* clears the Revise / Remove stack with breathing room */
      '}',
      /* Top-right action stack — Revise (SOW + bid) and Remove (bid). */
      '.scw-bid-review__cell-actions {',
      '  position: absolute;',
      '  top: 6px;',
      '  right: 6px;',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 4px;',
      '  align-items: flex-end;',
      '  z-index: 2;',
      '}',
      '.scw-bid-review__cell-action {',
      '  appearance: none;',
      '  border: 1px solid;',
      '  border-radius: 4px;',
      '  background: #fff;',
      '  font: 600 10.5px/1 system-ui, sans-serif;',
      '  padding: 3px 7px;',
      '  cursor: pointer;',
      '  letter-spacing: 0.02em;',
      '  white-space: nowrap;', /* never wrap inside an action button — keeps the absolute stack a predictable width */
      '}',
      '.scw-bid-review__cell-action--revise {',
      '  color: #0369a1;',
      '  border-color: #bae6fd;',
      '}',
      '.scw-bid-review__cell-action--revise:hover {',
      '  background: #f0f9ff; border-color: #38bdf8;',
      '}',
      '.scw-bid-review__cell-action--remove {',
      '  color: #b91c1c;',
      '  border-color: #fecaca;',
      '}',
      '.scw-bid-review__cell-action--remove:hover {',
      '  background: #fef2f2; border-color: #f87171;',
      '}',

      /* ── cabling chips ────────────────────────────────────────── */
      '.scw-bid-review__cabling-chip {',
      '  display: inline-block;',
      '  padding: 2px 7px;',
      '  border-radius: 3px;',
      '  font-size: 10px;',
      '  font-weight: 600;',
      '  margin-top: 4px;',
      '}',

      '.scw-bid-review__cabling-chip--on {',
      '  background: #dcfce7;',
      '  color: #166534;',
      '}',

      '.scw-bid-review__cabling-chip--off {',
      '  background: #f1f5f9;',
      '  color: #94a3b8;',
      '  font-weight: 400;',
      '}',

      /* ── status chips ──────────────────────────────────────── */
      '.scw-bid-review__chip {',
      '  display: inline-block;',
      '  padding: 1px 6px;',
      '  border-radius: 3px;',
      '  font-size: 10px;',
      '  font-weight: 600;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.3px;',
      '  margin-top: 3px;',
      '}',

      '.scw-bid-review__chip--matched {',
      '  background: #dcfce7;',
      '  color: #166534;',
      '}',

      '.scw-bid-review__chip--missing {',
      '  background: #fef3c7;',
      '  color: #92400e;',
      '}',

      '.scw-bid-review__chip--new {',
      '  background: #dbeafe;',
      '  color: #1e40af;',
      '}',

      '.scw-bid-review__chip--conflict {',
      '  background: #fee2e2;',
      '  color: #991b1b;',
      '}',

      /* ── row actions cell ──────────────────────────────────── */
      '.scw-bid-review__row-actions {',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 3px;',
      '}',

      /* ── action menus row ───────────────────────────────── */
      '.scw-bid-review__action-menus {',
      '  display: flex;',
      '  justify-content: flex-end;',
      '  gap: 4px;',
      '  margin-top: 2px;',
      '}',

      /* ── overflow menu (⋮ per action) ────────────────────── */
      '.scw-bid-review__overflow {',
      '  position: relative;',
      '}',

      '.scw-bid-review__overflow-trigger {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  gap: 3px;',
      '  padding: 3px 8px;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 4px;',
      '  background: #fff;',
      '  font: 600 10px/1.2 system-ui, sans-serif;',
      '  color: #475569;',
      '  cursor: pointer;',
      '  transition: background .15s, border-color .15s;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-review__overflow-trigger:hover {',
      '  background: #f1f5f9;',
      '  border-color: #94a3b8;',
      '}',

      '.scw-bid-review__overflow-dots {',
      '  font-size: 13px;',
      '  line-height: 1;',
      '  font-weight: 700;',
      '}',

      /* Trigger color variants */
      '.scw-bid-review__overflow-trigger--revise {',
      '  border-color: #93c5fd;',
      '  color: #1d4ed8;',
      '}',
      '.scw-bid-review__overflow-trigger--revise:hover {',
      '  background: #eff6ff;',
      '  border-color: #60a5fa;',
      '}',

      '.scw-bid-review__overflow-trigger--remove {',
      '  border-color: #fca5a5;',
      '  color: #dc2626;',
      '}',
      '.scw-bid-review__overflow-trigger--remove:hover {',
      '  background: #fef2f2;',
      '  border-color: #f87171;',
      '}',

      '.scw-bid-review__overflow-trigger--add {',
      '  border-color: #86efac;',
      '  color: #16a34a;',
      '}',
      '.scw-bid-review__overflow-trigger--add:hover {',
      '  background: #f0fdf4;',
      '  border-color: #4ade80;',
      '}',

      '.scw-bid-review__overflow-trigger--create {',
      '  border-color: #86efac;',
      '  color: #16a34a;',
      '}',
      '.scw-bid-review__overflow-trigger--create:hover {',
      '  background: #f0fdf4;',
      '  border-color: #4ade80;',
      '}',

      '.scw-bid-review__overflow-menu {',
      '  display: none;',
      '  position: absolute;',
      '  top: 100%;',
      '  right: 0;',
      '  z-index: 50;',
      '  margin-top: 2px;',
      '  min-width: 140px;',
      '  background: #fff;',
      '  border: 1px solid #e2e8f0;',
      '  border-radius: 6px;',
      '  box-shadow: 0 4px 12px rgba(0,0,0,.12);',
      '  padding: 4px 0;',
      '}',

      '.scw-bid-review__overflow--open .scw-bid-review__overflow-menu {',
      '  display: block;',
      '}',

      '.scw-bid-review__overflow-item {',
      '  display: block;',
      '  width: 100%;',
      '  text-align: left;',
      '  padding: 6px 12px;',
      '  border: none;',
      '  background: none;',
      '  font: 500 12px/1.3 system-ui, sans-serif;',
      '  color: #334155;',
      '  cursor: pointer;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-review__overflow-item:hover {',
      '  background: #f1f5f9;',
      '}',

      /* ── change request column header controls ────────────── */
      '.scw-bid-review__cr-col-title {',
      '  font-size: 13px;',
      '  font-weight: 700;',
      '  color: #0f172a;',
      '  margin-bottom: 4px;',
      '}',

      '.scw-bid-review__cr-col-actions {',
      '  display: flex;',
      '  flex-direction: column;',
      '  gap: 3px;',
      '}',

      '.scw-bid-review__btn--cr-submit {',
      '  background: #0891b2;',
      '  color: #fff;',
      '}',

      '.scw-bid-review__btn--cr-clear {',
      '  background: #e2e8f0;',
      '  color: #475569;',
      '}',

      /* ── change request cards (inline in actions column) ──── */
      '.scw-bid-cr-card {',
      '  background: #f0fdfa;',
      '  border: 1px solid #99f6e4;',
      '  border-left: 3px solid #0891b2;',
      '  border-radius: 4px;',
      '  padding: 5px 8px;',
      '  margin-top: 2px; margin-bottom: 2px;',
      '  font-size: 10px;',
      '  line-height: 1.35;',
      '  cursor: pointer;',
      '  transition: box-shadow .15s;',
      '}',
      '.scw-bid-cr-card:hover { box-shadow: 0 1px 4px rgba(0,0,0,.12); }',
      '.scw-bid-cr-card--removal {',
      '  background: #fef2f2;',
      '  border-color: #fca5a5;',
      '  border-left-color: #dc2626;',
      '}',
      '.scw-bid-cr-card--removal .scw-bid-cr-card__header {',
      '  color: #dc2626;',
      '}',
      '.scw-bid-cr-card--add {',
      '  background: #f0fdf4;',
      '  border-color: #86efac;',
      '  border-left-color: #16a34a;',
      '}',
      '.scw-bid-cr-card--add .scw-bid-cr-card__header {',
      '  color: #16a34a;',
      '}',

      '.scw-bid-cr-card__header {',
      '  font-weight: 700;',
      '  font-size: 9px;',
      '  text-transform: uppercase;',
      '  letter-spacing: .4px;',
      '  color: #0891b2;',
      '  margin-bottom: 3px;',
      '  position: relative;',
      '  padding-right: 14px;',
      '}',
      '.scw-bid-cr-card__dismiss {',
      '  position: absolute; top: -2px; right: -4px;',
      '  background: none; border: none; cursor: pointer;',
      '  font-size: 13px; line-height: 1; color: #94a3b8;',
      '  padding: 0 2px;',
      '}',
      '.scw-bid-cr-card__dismiss:hover { color: #dc2626; }',

      '.scw-bid-cr-card__item-label {',
      '  font-weight: 700;',
      '  font-size: 11px;',
      '  color: #0f172a;',
      '  margin-bottom: 2px;',
      '}',

      '.scw-bid-cr-card__row {',
      '  display: flex;',
      '  align-items: baseline;',
      '  gap: 3px;',
      '  padding: 1px 0;',
      '}',

      '.scw-bid-cr-card__label {',
      '  font-weight: 600;',
      '  color: #475569;',
      '  white-space: nowrap;',
      '}',

      '.scw-bid-cr-card__from {',
      '  color: #dc2626;',
      '  text-decoration: line-through;',
      '}',

      '.scw-bid-cr-card__arrow {',
      '  color: #94a3b8;',
      '  flex-shrink: 0;',
      '}',

      '.scw-bid-cr-card__to {',
      '  color: #059669;',
      '  font-weight: 600;',
      '}',

      '.scw-bid-cr-card__notes {',
      '  color: #64748b;',
      '  font-style: italic;',
      '  margin-top: 3px;',
      '  padding-top: 3px;',
      '  border-top: 1px solid #ccfbf1;',
      '}',

      /* ── empty & loading states ────────────────────────────── */
      '.scw-bid-review__empty-state {',
      '  text-align: center;',
      '  padding: 40px 20px;',
      '  color: #94a3b8;',
      '  font-size: 14px;',
      '}',

      '.scw-bid-review__loading {',
      '  text-align: center;',
      '  padding: 32px 20px;',
      '  color: #64748b;',
      '  font-size: 13px;',
      '}',

      '.scw-bid-review__loading::after {',
      '  content: "";',
      '  display: inline-block;',
      '  width: 14px;',
      '  height: 14px;',
      '  border: 2px solid #cbd5e1;',
      '  border-top-color: #3b82f6;',
      '  border-radius: 50%;',
      '  margin-left: 8px;',
      '  vertical-align: middle;',
      '  animation: scwBidSpin .7s linear infinite;',
      '}',

      '@keyframes scwBidSpin {',
      '  to { transform: rotate(360deg); }',
      '}',

      /* ── toast ──────────────────────────────────────────────── */
      '.scw-bid-review__toast {',
      '  position: fixed;',
      '  bottom: 24px;',
      '  left: 50%;',
      '  transform: translateX(-50%);',
      '  z-index: 100000;',
      '  padding: 10px 20px;',
      '  border-radius: 6px;',
      '  font: 600 13px/1.3 system-ui, sans-serif;',
      '  color: #fff;',
      '  box-shadow: 0 4px 16px rgba(0,0,0,0.25);',
      '  transition: opacity .3s;',
      '}',

      '.scw-bid-review__toast--success {',
      '  background: #16a34a;',
      '}',

      '.scw-bid-review__toast--error {',
      '  background: #dc2626;',
      '}',

      '.scw-bid-review__toast--info {',
      '  background: #2563eb;',
      '}',

      /* ── bid status bar ──────────────────────────────────── */
      '.scw-bid-review__status-bar {',
      '  display: flex;',
      '  flex-wrap: wrap;',
      '  gap: 10px;',
      '  margin-bottom: 14px;',
      '  padding: 10px 14px;',
      '  background: #f8fafc;',
      '  border: 1px solid #e2e8f0;',
      '  border-radius: 6px;',
      '}',
      '.scw-bid-review__status-chip {',
      '  display: flex;',
      '  align-items: center;',
      '  gap: 8px;',
      '  padding: 4px 0;',
      '}',
      '.scw-bid-review__status-pkg {',
      '  font-weight: 600;',
      '  font-size: 13px;',
      '  color: #334155;',
      '}',
      '.scw-bid-review__status-badge {',
      '  display: inline-block;',
      '  padding: 2px 10px;',
      '  border-radius: 12px;',
      '  font-size: 11px;',
      '  font-weight: 600;',
      '  text-transform: uppercase;',
      '  letter-spacing: 0.3px;',
      '  background: #e2e8f0;',
      '  color: #475569;',
      '}',
      '.scw-bid-review__status-badge[data-status="submitted"] {',
      '  background: #dcfce7;',
      '  color: #166534;',
      '}',
      '.scw-bid-review__status-badge[data-status="pending"] {',
      '  background: #fef3c7;',
      '  color: #92400e;',
      '}',
      '.scw-bid-review__status-badge[data-status="draft"] {',
      '  background: #dbeafe;',
      '  color: #1e40af;',
      '}',
      '.scw-bid-review__status-badge[data-status="rejected"] {',
      '  background: #fee2e2;',
      '  color: #991b1b;',
      '}',

    ].join('\n');

    var style = document.createElement('style');
    style.id = CFG.cssId;
    style.textContent = css;
    document.head.appendChild(style);
  };

})();
