/*** WORKSHEET V2 — STYLES ****************************************************
 *
 * Phase 3.A — compact horizontal-row layout. Each card is a single
 * grid row with fixed/flex columns:
 *
 *   [label fixed] [product flex] [qty fixed] [rate fixed] [ext fixed]
 *     [notes flex] [chevron fixed]
 *
 * All v2 CSS scoped under `.scw-ws-v2` AND uses !important on the
 * structural rules — Knack's scene-level styles target generic tags
 * (div, input, textarea, button) aggressively and would otherwise
 * collapse the layout.
 ****************************************************************************/
(function () {
  'use strict';

  var STYLE_ID = 'scw-ws-v2-css';
  if (document.getElementById(STYLE_ID)) return;

  var css = [
    /* ── Container ──────────────────────────────────────────── */
    '.scw-ws-v2 {',
    '  margin: 24px 0 !important;',
    '  padding: 0 !important;',
    '  background: var(--scw-surface-base, #fff) !important;',
    '  border: 2px dashed #c084fc !important;',
    '  border-radius: 8px !important;',
    '  overflow: hidden !important;',
    '  font: 13px/1.4 system-ui, -apple-system, sans-serif !important;',
    '  color: var(--scw-text-default, #1f2937) !important;',
    '  display: block !important;',
    '  box-sizing: border-box !important;',
    '}',
    '.scw-ws-v2 * { box-sizing: border-box; }',

    /* ── WIP banner ─────────────────────────────────────────── */
    '.scw-ws-v2-banner {',
    '  display: flex !important; align-items: center !important; gap: 10px !important;',
    '  padding: 8px 14px !important;',
    '  background: #faf5ff !important;',
    '  border-bottom: 1px solid #e9d5ff !important;',
    '  font-weight: 600 !important; color: #6b21a8 !important;',
    '}',
    '.scw-ws-v2-banner .scw-ws-v2-pill {',
    '  display: inline-block !important;',
    '  padding: 2px 8px !important;',
    '  background: #6b21a8 !important; color: #fff !important;',
    '  border-radius: 4px !important;',
    '  font-size: 10px !important; font-weight: 700 !important; letter-spacing: 0.04em !important;',
    '  text-transform: uppercase !important;',
    '}',
    '.scw-ws-v2-banner .scw-ws-v2-count {',
    '  margin-left: auto !important;',
    '  font-weight: 500 !important; color: #4b5563 !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '}',

    /* ── Body / card list ───────────────────────────────────── */
    '.scw-ws-v2-body {',
    '  padding: 0 !important;',
    '  max-height: 680px !important;',
    '  overflow: auto !important;',
    '  display: block !important;',
    '}',
    '.scw-ws-v2-empty {',
    '  padding: 20px !important;',
    '  text-align: center !important;',
    '  color: #6b7280 !important;',
    '  font-style: italic !important;',
    '}',

    /* ── Card (row container) ───────────────────────────────── */
    '.scw-ws-v2-card {',
    '  display: block !important;',
    '  border-bottom: 1px solid var(--scw-border-subtle, #e2e8f0) !important;',
    '  background: #fff !important;',
    '  transition: background-color 100ms ease !important;',
    '}',
    '.scw-ws-v2-card:hover {',
    '  background: var(--scw-surface-subtle, #f8fafc) !important;',
    '}',
    /* Alternating zebra to help scan long lists */
    '.scw-ws-v2-card:nth-child(even) {',
    '  background: #fafbfc !important;',
    '}',
    '.scw-ws-v2-card:nth-child(even):hover {',
    '  background: var(--scw-surface-muted, #f1f5f9) !important;',
    '}',

    /* ── Row grid ───────────────────────────────────────────── */
    /* DEFAULT bucket (Networking / Other Equipment / Mounting Hardware /
       any non-special bucket). No label column, no chips. */
    '.scw-ws-v2-row--default {',
    '  display: grid !important;',
    '  grid-template-columns:',
    '    minmax(160px, 1.4fr)  /* product */',
    '    minmax(160px, 1.6fr)  /* labor desc */',
    '    64px              /* qty     */',
    '    78px              /* subBid  */',
    '    64px              /* +Hrs    */',
    '    64px              /* +Mat    */',
    '    72px              /* fee     */',
    '    52px              /* sow     */',
    '    28px              /* chevron */ !important;',
    '  gap: 6px !important;',
    '  align-items: center !important;',
    '  padding: 4px 10px !important;',
    '  min-height: 40px !important;',
    '}',
    /* CAM/READER bucket — adds label + chip-stack columns. */
    '.scw-ws-v2-row--cam {',
    '  display: grid !important;',
    '  grid-template-columns:',
    '    64px                  /* label   */',
    '    minmax(140px, 1.4fr)  /* product */',
    '    100px                 /* chips   */',
    '    minmax(120px, 1.4fr)  /* labor desc */',
    '    64px 78px 64px 64px 72px 52px 28px !important;',
    '  gap: 6px !important;',
    '  align-items: center !important;',
    '  padding: 4px 10px !important;',
    '  min-height: 40px !important;',
    '}',
    /* SERVICES bucket — replaces product with a "Service" tag. Keeps
       qty / money / fee / sow because service rows still carry a
       dollar value. */
    '.scw-ws-v2-row--services {',
    '  display: grid !important;',
    '  grid-template-columns:',
    '    80px                  /* "Service" tag */',
    '    minmax(220px, 1.6fr)  /* description */',
    '    64px 78px 64px 64px 72px 52px 28px !important;',
    '  gap: 6px !important;',
    '  align-items: center !important;',
    '  padding: 4px 10px !important;',
    '  min-height: 40px !important;',
    '}',
    /* ASSUMPTIONS bucket — almost full-width text. No money. */
    '.scw-ws-v2-row--assumptions {',
    '  display: grid !important;',
    '  grid-template-columns:',
    '    100px            /* "Assumption" tag */',
    '    1fr              /* text */',
    '    28px             /* chevron */ !important;',
    '  gap: 6px !important;',
    '  align-items: center !important;',
    '  padding: 4px 10px !important;',
    '  min-height: 40px !important;',
    '}',

    /* Bucket tag cell ("Service" / "Assumption") */
    '.scw-ws-v2-cell--tag {',
    '  font: 700 10px/1.2 system-ui, -apple-system, sans-serif !important;',
    '  letter-spacing: 0.06em !important;',
    '  text-transform: uppercase !important;',
    '  color: #6b21a8 !important;',
    '  background: #faf5ff !important;',
    '  border: 1px solid #e9d5ff !important;',
    '  border-radius: 4px !important;',
    '  padding: 4px 8px !important;',
    '  text-align: center !important;',
    '  white-space: nowrap !important;',
    '}',

    /* ── Cells ──────────────────────────────────────────────── */
    '.scw-ws-v2-cell {',
    '  display: block !important;',
    '  min-width: 0 !important;', /* allows ellipsis on flex children */
    '  font-size: 13px !important;',
    '  line-height: 1.3 !important;',
    '}',

    '.scw-ws-v2-cell--label {',
    '  font-weight: 700 !important;',
    '  color: #07467c !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '  white-space: nowrap !important;',
    '  overflow: hidden !important;',
    '  text-overflow: ellipsis !important;',
    '}',

    '.scw-ws-v2-cell--product {',
    '  color: var(--scw-text-default, #1f2937) !important;',
    '  white-space: nowrap !important;',
    '  overflow: hidden !important;',
    '  text-overflow: ellipsis !important;',
    '}',

    '.scw-ws-v2-cell--num,',
    '.scw-ws-v2-cell--ext {',
    '  text-align: right !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '}',

    '.scw-ws-v2-cell--ext {',
    '  font-weight: 600 !important;',
    '  color: #07467c !important;',
    '  padding: 5px 8px !important;', /* match input vertical rhythm */
    '}',

    /* ── Inputs ─────────────────────────────────────────────── */
    '.scw-ws-v2-input {',
    '  display: block !important;',
    '  width: 100% !important;',
    '  box-sizing: border-box !important;',
    '  padding: 4px 6px !important;',
    '  border: 1px solid transparent !important;', /* hide chrome until hover/focus — looks like v1's inline cells */
    '  border-radius: 3px !important;',
    '  background: transparent !important;',
    '  font: inherit !important;',
    '  color: var(--scw-text-default, #1f2937) !important;',
    '  min-height: 26px !important;',
    '  transition: border-color 100ms ease, background-color 100ms ease, box-shadow 100ms ease !important;',
    '}',
    '.scw-ws-v2-card:hover .scw-ws-v2-input {',
    '  border-color: var(--scw-border-subtle, #e2e8f0) !important;',
    '  background: #fff !important;',
    '}',
    '.scw-ws-v2-input:focus {',
    '  outline: none !important;',
    '  border-color: #93c5fd !important;',
    '  background: #fff !important;',
    '  box-shadow: 0 0 0 2px rgba(147, 197, 253, 0.25) !important;',
    '}',

    '.scw-ws-v2-input--num {',
    '  text-align: right !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '}',

    '.scw-ws-v2-input--notes {',
    '  white-space: nowrap !important;',
    '  overflow: hidden !important;',
    '  text-overflow: ellipsis !important;',
    '}',

    /* ── Save state flashes ─────────────────────────────────── */
    '.scw-ws-v2-input--saving {',
    '  background-color: #dcfce7 !important;',
    '  border-color: #4ade80 !important;',
    '}',
    '.scw-ws-v2-input--error {',
    '  background-color: #fef2f2 !important;',
    '  border-color: #fca5a5 !important;',
    '  box-shadow: 0 0 0 2px rgba(252, 165, 165, 0.25) !important;',
    '}',

    /* ── L1 group block (MDF/IDF accordion) ─────────────────── */
    '.scw-ws-v2-l1 {',
    '  display: block !important;',
    '  border-bottom: 1px solid var(--scw-border-default, #cbd5e1) !important;',
    '}',
    '.scw-ws-v2-l1:last-child {',
    '  border-bottom: 0 !important;',
    '}',

    /* L1 header — button styled to look like a v1 accordion header */
    '.scw-ws-v2-l1-head {',
    '  display: flex !important;',
    '  align-items: center !important;',
    '  gap: 10px !important;',
    '  width: 100% !important;',
    '  padding: 8px 14px !important;',
    '  background: linear-gradient(180deg, #0f4c75 0%, #07467c 100%) !important;',
    '  color: #fff !important;',
    '  border: 0 !important;',
    '  border-left: 4px solid #ed8326 !important;', /* orange L1 accent — matches v1 */
    '  font: 700 13px/1 system-ui, -apple-system, sans-serif !important;',
    '  letter-spacing: 0.02em !important;',
    '  text-align: left !important;',
    '  cursor: pointer !important;',
    '  transition: background 120ms ease !important;',
    '}',
    '.scw-ws-v2-l1-head:hover {',
    '  background: linear-gradient(180deg, #07467c 0%, #053659 100%) !important;',
    '}',
    '.scw-ws-v2-l1-head--synthetic {',
    /* Slate accent for synthetic groups (Project Wide Services etc.) */
    '  background: linear-gradient(180deg, #5f6b7a 0%, #475569 100%) !important;',
    '  border-left-color: #94a3b8 !important;',
    '}',
    '.scw-ws-v2-l1-head--synthetic:hover {',
    '  background: linear-gradient(180deg, #475569 0%, #334155 100%) !important;',
    '}',
    '.scw-ws-v2-l1-chevron {',
    '  display: inline-flex !important;',
    '  align-items: center !important;',
    '  justify-content: center !important;',
    '  width: 16px !important; height: 16px !important;',
    '  flex: 0 0 auto !important;',
    '  transition: transform 150ms ease !important;',
    '}',
    '.scw-ws-v2-l1-head--open .scw-ws-v2-l1-chevron {',
    '  transform: rotate(180deg) !important;',
    '}',
    '.scw-ws-v2-l1-label {',
    '  flex: 1 1 auto !important;',
    '  white-space: nowrap !important;',
    '  overflow: hidden !important;',
    '  text-overflow: ellipsis !important;',
    '}',
    '.scw-ws-v2-l1-count {',
    '  flex: 0 0 auto !important;',
    '  padding: 2px 8px !important;',
    '  background: rgba(255, 255, 255, 0.18) !important;',
    '  border-radius: 10px !important;',
    '  font-size: 11px !important;',
    '  font-weight: 700 !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '  min-width: 22px !important;',
    '  text-align: center !important;',
    '}',

    /* L1 body — collapsed by default; opens via .scw-ws-v2-l1--open */
    '.scw-ws-v2-l1-body {',
    '  display: none !important;',
    '  background: #fff !important;',
    '}',
    '.scw-ws-v2-l1--open .scw-ws-v2-l1-body {',
    '  display: block !important;',
    '}',

    /* ── L2 sub-header (proposal bucket) ────────────────────── */
    '.scw-ws-v2-l2-head {',
    '  display: flex !important;',
    '  align-items: center !important;',
    '  gap: 8px !important;',
    '  padding: 4px 14px !important;',
    '  background: #f8fafc !important;',
    '  border-top: 1px solid var(--scw-border-subtle, #e2e8f0) !important;',
    '  border-bottom: 1px solid var(--scw-border-subtle, #e2e8f0) !important;',
    '  font: 700 11px/1.2 system-ui, -apple-system, sans-serif !important;',
    '  color: #0f4c75 !important;',
    '  text-transform: uppercase !important;',
    '  letter-spacing: 0.06em !important;',
    '}',
    '.scw-ws-v2-l1-body > .scw-ws-v2-l2-head:first-child {',
    '  border-top: 0 !important;',
    '}',
    '.scw-ws-v2-l2-label {',
    '  flex: 1 1 auto !important;',
    '  white-space: nowrap !important;',
    '  overflow: hidden !important;',
    '  text-overflow: ellipsis !important;',
    '}',
    '.scw-ws-v2-l2-count {',
    '  flex: 0 0 auto !important;',
    '  color: var(--scw-text-caption, #64748b) !important;',
    '  font-weight: 500 !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '}',

    /* ── Cell extras (fee, sow, stack-total) ──────────────────── */
    '.scw-ws-v2-cell--fee {',
    '  padding: 5px 6px !important;',
    '  font-weight: 600 !important;',
    '  color: #07467c !important;',
    '  text-align: right !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '}',
    '.scw-ws-v2-cell--sow {',
    '  padding: 5px 6px !important;',
    '  color: var(--scw-text-caption, #64748b) !important;',
    '  font-size: 11px !important;',
    '  white-space: nowrap !important;',
    '  overflow: hidden !important;',
    '  text-overflow: ellipsis !important;',
    '}',
    '.scw-ws-v2-cell--stack {',
    '  display: flex !important;',
    '  flex-direction: column !important;',
    '  gap: 1px !important;',
    '  min-width: 0 !important;',
    '}',
    '.scw-ws-v2-stack-total {',
    '  font-size: 10px !important;',
    '  color: var(--scw-text-caption, #64748b) !important;',
    '  font-variant-numeric: tabular-nums !important;',
    '  text-align: right !important;',
    '  padding: 0 6px !important;',
    '  min-height: 12px !important;',
    '}',

    /* ── Chip stack (cam/reader summary booleans) ────────────── */
    '.scw-ws-v2-cell--chips {',
    '  display: flex !important;',
    '  flex-direction: row !important;',
    '  flex-wrap: wrap !important;',
    '  gap: 3px !important;',
    '  align-items: center !important;',
    '  min-width: 0 !important;',
    '}',
    '.scw-ws-v2-chip {',
    '  display: inline-flex !important;',
    '  align-items: center !important;',
    '  justify-content: center !important;',
    '  padding: 2px 7px !important;',
    '  border: 1px solid transparent !important;',
    '  border-radius: 10px !important;',
    '  font: 700 10px/1.2 system-ui, -apple-system, sans-serif !important;',
    '  letter-spacing: 0.04em !important;',
    '  text-transform: uppercase !important;',
    '  cursor: pointer !important;',
    '  user-select: none !important;',
    '  transition: background-color 100ms ease, color 100ms ease, transform 60ms ease !important;',
    '  min-height: 18px !important;',
    '}',
    '.scw-ws-v2-chip:active { transform: scale(0.95) !important; }',
    '.scw-ws-v2-chip--yes {',
    '  background: #16a34a !important;',
    '  color: #fff !important;',
    '  border-color: #15803d !important;',
    '}',
    '.scw-ws-v2-chip--no {',
    '  background: #e2e8f0 !important;',
    '  color: #64748b !important;',
    '  border-color: #cbd5e1 !important;',
    '}',
    '.scw-ws-v2-chip--saving {',
    '  box-shadow: 0 0 0 2px rgba(74, 222, 128, 0.45) !important;',
    '}',
    '.scw-ws-v2-chip--error {',
    '  background: #fef2f2 !important;',
    '  color: #b91c1c !important;',
    '  border-color: #fca5a5 !important;',
    '}',

    /* ── Detail panel (expand body under each card) ──────────── */
    '.scw-ws-v2-detail {',
    '  display: none !important;',
    '  padding: 10px 14px 12px !important;',
    '  background: #f8fafc !important;',
    '  border-top: 1px dashed var(--scw-border-default, #cbd5e1) !important;',
    '}',
    '.scw-ws-v2-card--open .scw-ws-v2-detail {',
    '  display: block !important;',
    '}',
    '.scw-ws-v2-detail-grid {',
    '  display: grid !important;',
    '  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)) !important;',
    '  gap: 8px 16px !important;',
    '}',
    '.scw-ws-v2-detail-field {',
    '  display: flex !important;',
    '  flex-direction: column !important;',
    '  gap: 2px !important;',
    '  min-width: 0 !important;',
    '}',
    '.scw-ws-v2-detail-label {',
    '  font: 700 10px/1.2 system-ui, -apple-system, sans-serif !important;',
    '  letter-spacing: 0.05em !important;',
    '  text-transform: uppercase !important;',
    '  color: var(--scw-text-caption, #64748b) !important;',
    '}',
    /* Editable connection-field button — looks like a click target */
    '.scw-ws-v2-conn-btn {',
    '  display: flex !important; align-items: center !important; gap: 8px !important;',
    '  padding: 5px 8px !important;',
    '  background: #fff !important;',
    '  border: 1px solid var(--scw-border-default, #cbd5e1) !important;',
    '  border-radius: 4px !important;',
    '  font: 13px/1.3 system-ui, -apple-system, sans-serif !important;',
    '  color: var(--scw-text-default, #1f2937) !important;',
    '  cursor: pointer !important;',
    '  text-align: left !important;',
    '  min-height: 26px !important;',
    '  transition: border-color 100ms ease, background 100ms ease !important;',
    '}',
    '.scw-ws-v2-conn-btn:hover {',
    '  border-color: #93c5fd !important;',
    '  background: #eff6ff !important;',
    '}',
    '.scw-ws-v2-conn-btn-val {',
    '  flex: 1 1 auto;',
    '  min-width: 0;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  white-space: nowrap;',
    '}',
    '.scw-ws-v2-conn-btn-edit {',
    '  flex: 0 0 auto;',
    '  font: 700 9px/1 system-ui, sans-serif !important;',
    '  letter-spacing: 0.06em !important;',
    '  text-transform: uppercase !important;',
    '  color: #07467c !important;',
    '  background: #eff6ff !important;',
    '  padding: 2px 5px !important;',
    '  border-radius: 3px !important;',
    '}',

    /* Mounting Hardware widget — chip list with edit links + add */
    '.scw-ws-v2-mh-list {',
    '  display: flex !important; flex-wrap: wrap !important; gap: 4px !important;',
    '  align-items: center !important;',
    '  padding: 4px 0 !important;',
    '}',
    '.scw-ws-v2-mh-empty {',
    '  font-size: 12px !important; color: #94a3b8 !important;',
    '  padding: 2px 4px !important;',
    '}',
    '.scw-ws-v2-mh-chip {',
    '  display: inline-flex; align-items: center;',
    '  padding: 3px 8px !important;',
    '  background: #eff6ff !important; color: #07467c !important;',
    '  border: 1px solid #bfdbfe !important;',
    '  border-radius: 10px !important;',
    '  font: 500 11px/1.2 system-ui, sans-serif !important;',
    '  text-decoration: none !important;',
    '  transition: background 100ms ease, border-color 100ms ease;',
    '}',
    '.scw-ws-v2-mh-chip:hover {',
    '  background: #dbeafe !important; border-color: #93c5fd !important;',
    '  text-decoration: none !important;',
    '}',
    '.scw-ws-v2-mh-add {',
    '  display: inline-flex; align-items: center;',
    '  padding: 3px 8px !important;',
    '  background: #fff !important; color: #07467c !important;',
    '  border: 1px dashed #cbd5e1 !important;',
    '  border-radius: 10px !important;',
    '  font: 700 10px/1.2 system-ui, sans-serif !important;',
    '  letter-spacing: 0.04em; text-transform: uppercase;',
    '  text-decoration: none !important;',
    '  transition: background 100ms ease, border-color 100ms ease;',
    '}',
    '.scw-ws-v2-mh-add:hover {',
    '  background: #eaf2fb !important; border-color: #07467c !important;',
    '  border-style: solid !important;',
    '  text-decoration: none !important;',
    '}',

    '.scw-ws-v2-detail-field--ro .scw-ws-v2-display {',
    '  padding: 5px 8px !important;',
    '  font-size: 12px !important;',
    '  color: var(--scw-text-default, #1f2937) !important;',
    '  background: #fff !important;',
    '  border: 1px solid var(--scw-border-subtle, #e2e8f0) !important;',
    '  border-radius: 4px !important;',
    '  min-height: 26px !important;',
    '}',

    /* ── Chevron ────────────────────────────────────────────── */
    '.scw-ws-v2-chevron {',
    '  display: inline-flex !important;',
    '  align-items: center !important;',
    '  justify-content: center !important;',
    '  width: 24px !important;',
    '  height: 24px !important;',
    '  padding: 0 !important;',
    '  margin: 0 !important;',
    '  border: 0 !important;',
    '  background: transparent !important;',
    '  color: var(--scw-text-caption, #64748b) !important;',
    '  cursor: pointer !important;',
    '  border-radius: 4px !important;',
    '  transition: transform 150ms ease, background-color 100ms ease !important;',
    '}',
    '.scw-ws-v2-chevron:hover {',
    '  background: var(--scw-surface-muted, #f1f5f9) !important;',
    '  color: #07467c !important;',
    '}',
    '.scw-ws-v2-card--open .scw-ws-v2-chevron {',
    '  transform: rotate(90deg) !important;',
    '}'
  ].join('\n');

  var s = document.createElement('style');
  s.id = STYLE_ID;
  s.textContent = css;
  document.head.appendChild(s);
})();
/*** END WORKSHEET V2 — STYLES ************************************************/
