/*** BID REVIEW V2 — STYLES ***************************************************
 *
 * Self-scoped CSS for the v2 panel. All rules nest under
 * .scw-bid-review-v2 so they cannot leak into v1 or the rest of the
 * scene.
 *
 * Banner mirrors worksheet-v2's WIP pill so the parallel build reads
 * consistently across the codebase.
 ****************************************************************************/
(function () {
  'use strict';

  var ns = window.SCW.bidReviewV2;
  if (!ns || !ns.CONFIG) return;

  if (document.getElementById(ns.CONFIG.cssId)) return;

  var css = [
    /* ── Container + WIP banner ─────────────────────────────── */
    '.scw-bid-review-v2 {',
    '  margin: 24px 0 32px;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;',
    '  color: #0f172a;',
    '}',
    '.scw-bid-review-v2-banner {',
    '  display: flex; align-items: center; gap: 8px;',
    '  padding: 10px 14px;',
    '  background: #f8fafc; border: 1px solid #e2e8f0;',
    '  border-radius: 8px 8px 0 0;',
    '  font-size: 13px; color: #334155;',
    '}',
    '.scw-bid-review-v2-pill {',
    '  display: inline-flex; align-items: center; gap: 4px;',
    '  padding: 2px 8px;',
    '  background: #6b21a8; color: #fff;',
    '  border-radius: 999px;',
    '  font-size: 11px; font-weight: 600; letter-spacing: 0.04em;',
    '  text-transform: uppercase;',
    '}',
    '.scw-bid-review-v2-count {',
    '  margin-left: auto;',
    '  color: #64748b; font-size: 12px;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2-body {',
    '  padding: 16px;',
    '  background: #fff;',
    '  border: 1px solid #e2e8f0; border-top: none;',
    '  border-radius: 0 0 8px 8px;',
    '  min-height: 80px;',
    '}',
    '.scw-bid-review-v2-empty {',
    '  color: #94a3b8; font-style: italic; font-size: 13px;',
    '  text-align: center; padding: 16px 0;',
    '}',
    /* ── SOW section card ───────────────────────────────────── */
    '.scw-bid-review-v2__sow {',
    '  margin-bottom: 32px;',
    '  border: 1px solid #cbd5e1; border-radius: 10px;',
    '  overflow: hidden; background: #fff;',
    '  box-shadow: 0 1px 2px rgba(15,23,42,0.04);',
    '}',
    '.scw-bid-review-v2__sow-header {',
    '  display: flex; align-items: baseline; gap: 12px;',
    '  padding: 14px 20px;',
    '  background: linear-gradient(180deg,#2d6aa3 0%,#295f91 100%);',
    '  color: #fff;',
    '  font-size: 15px; font-weight: 700; letter-spacing: 0.01em;',
    '}',
    '.scw-bid-review-v2__sow-name { flex: 0 0 auto; }',
    '.scw-bid-review-v2__sow-meta {',
    '  margin-left: auto;',
    '  font-size: 11px; font-weight: 500;',
    '  color: rgba(255,255,255,0.85);',
    '  font-variant-numeric: tabular-nums;',
    '}',
    /* ── Table + thead ─────────────────────────────────────── */
    '.scw-bid-review-v2__table {',
    '  width: 100%; border-collapse: separate; border-spacing: 0;',
    '  font-size: 12px;',
    '}',
    '.scw-bid-review-v2__th {',
    '  background: #f1f5f9; color: #475569; font-weight: 600;',
    '  text-align: left; padding: 14px 22px !important;',
    '  border-bottom: 1px solid #cbd5e1;',
    '  font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em;',
    '}',
    '.scw-bid-review-v2__th--label { width: 70px; }',
    '.scw-bid-review-v2__th--sow {',
    '  width: 280px; background: #e3edf6; color: #295f91;',
    '  border-right: 2px solid #cbd5e1;',
    '}',
    /* ── L1 group header (MDF/IDF) ─────────────────────────── */
    '.scw-bid-review-v2__group-header { cursor: pointer; user-select: none; -webkit-user-select: none; }',
    '.scw-bid-review-v2__group-header td {',
    '  position: relative;',
    '  background: #f1f5f9; padding: 0;',
    '  font-weight: 700; font-size: 13px; color: #334155;',
    '  border-top: 1px solid #cbd5e1;',
    '  border-bottom: 1px solid #cbd5e1;',
    '  border-left: 4px solid #295f91;',
    '}',
    '.scw-bid-review-v2__group-header:first-child td { border-top: none; }',
    '.scw-bid-review-v2__group-header:hover td { background: #e8edf3; }',
    '.scw-bid-review-v2__grp-inner {',
    '  display: flex; align-items: center; gap: 10px;',
    '  padding: 12px 18px;',
    '}',
    '.scw-bid-review-v2__grp-chevron {',
    '  display: inline-flex; align-items: center; flex: 0 0 auto;',
    '  color: #295f91; transition: transform 220ms ease;',
    '}',
    '.scw-bid-review-v2__group-header--collapsed .scw-bid-review-v2__grp-chevron {',
    '  transform: rotate(-90deg);',
    '}',
    '.scw-bid-review-v2__grp-title { flex: 1 1 auto; }',
    '.scw-bid-review-v2__grp-count {',
    '  display: inline-block; padding: 2px 9px;',
    '  font-size: 11px; font-weight: 600; line-height: 1.4;',
    '  border-radius: 999px;',
    '  background: rgba(41,95,145,0.12);',
    '  border: 1px solid rgba(41,95,145,0.22);',
    '  color: #295f91;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    /* ── L2 sub-group header (proposal bucket) ─────────────── */
    '.scw-bid-review-v2__subgroup-header td {',
    '  background: #f8fafc; padding: 0;',
    '  border-bottom: 1px solid #e2e8f0;',
    '}',
    '.scw-bid-review-v2__subgrp-inner {',
    '  display: flex; align-items: center; gap: 8px;',
    '  padding: 9px 18px 9px 34px;',
    '}',
    '.scw-bid-review-v2__subgrp-title {',
    '  font-size: 11px; font-weight: 600; color: #475569;',
    '  text-transform: uppercase; letter-spacing: 0.04em;',
    '}',
    '.scw-bid-review-v2__subgrp-count {',
    '  display: inline-block; padding: 1px 7px;',
    '  font-size: 10px; font-weight: 600; line-height: 1.4;',
    '  border-radius: 999px; background: #e2e8f0; color: #64748b;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__row--hidden,',
    '.scw-bid-review-v2__subgroup-header--hidden { display: none !important; }',
    /* ── Data rows ─────────────────────────────────────────── */
    '.scw-bid-review-v2__row td {',
    '  border-bottom: 1px solid #e2e8f0;',
    '  vertical-align: top;',
    '}',
    '.scw-bid-review-v2__row--expandable { cursor: pointer; }',
    '.scw-bid-review-v2__row--expandable:hover td {',
    '  background-image: linear-gradient(rgba(41,95,145,0.04), rgba(41,95,145,0.04));',
    '}',
    '.scw-bid-review-v2__row--open td {',
    '  background-image: linear-gradient(rgba(41,95,145,0.06), rgba(41,95,145,0.06));',
    '  border-bottom-color: #295f91 !important;',
    '}',
    /* Expand row hosts worksheet-v2 card inline */
    '.scw-bid-review-v2__expand-row td {',
    '  background: #f1f5f9; padding: 12px 16px;',
    '  border-bottom: 1px solid #cbd5e1;',
    '  border-top: none;',
    '}',
    '.scw-bid-review-v2__expand-loading {',
    '  padding: 14px; color: #64748b; font-size: 12px;',
    '  text-align: center; font-style: italic;',
    '}',
    /* The injected worksheet-v2 card carries its own styles; just
       give it some breathing room inside the host cell. */
    '.scw-bid-review-v2__expand-cell .scw-ws-v2-card {',
    '  margin: 0; max-width: 100%;',
    '}',
    /* Line-item label cell (E-001, etc) */
    '.scw-bid-review-v2__row-label-cell {',
    '  padding: 20px 16px !important;',
    '  background: #f8fafc;',
    '  border-right: 1px solid #e2e8f0;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__row-label {',
    '  font-weight: 600; color: #0f172a; font-size: 12px;',
    '}',
    /* ── SOW item cell — editable anchor column ────────────── */
    '.scw-bid-review-v2__sow-cell {',
    '  padding: 20px 22px !important;',
    '  background: #f4f8fc; border-right: 2px solid #cbd5e1;',
    '  width: 280px; min-width: 240px;',
    '}',
    '.scw-bid-review-v2__sow-cell--empty {',
    '  background: #fafafa; text-align: center; color: #cbd5e1;',
    '}',
    '.scw-bid-review-v2__sow-product {',
    '  font-weight: 600; font-size: 13px; color: #0f172a;',
    '  margin-bottom: 10px; line-height: 1.35;',
    '  overflow-wrap: anywhere; word-break: break-word;',
    '}',
    '.scw-bid-review-v2__sow-numbers {',
    '  display: flex; gap: 16px; align-items: center;',
    '  margin-bottom: 10px;',
    '}',
    '.scw-bid-review-v2__sow-num {',
    '  display: inline-flex; align-items: center; gap: 5px;',
    '  font-size: 12px; color: #334155;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__sow-num label {',
    '  color: #64748b; font-size: 10px;',
    '  font-weight: 600;',
    '}',
    '.scw-bid-review-v2__sow-desc-wrap { margin-top: 4px; }',
    /* ── Bid cells (read-only) ─────────────────────────────── */
    '.scw-bid-review-v2__cell {',
    '  padding: 20px 22px !important;',
    '  border-right: 1px solid #f1f5f9; min-width: 220px;',
    '  background: #fff;',
    '}',
    '.scw-bid-review-v2__cell:last-child { border-right: none; }',
    '.scw-bid-review-v2__cell--empty {',
    '  background: #fafafa; text-align: center; color: #cbd5e1;',
    '}',
    '.scw-bid-review-v2__cell-empty-mark { font-size: 18px; line-height: 1; }',
    '.scw-bid-review-v2__cell-product {',
    '  font-weight: 600; font-size: 13px; color: #0f172a;',
    '  margin-bottom: 10px; line-height: 1.35;',
    '  overflow-wrap: anywhere; word-break: break-word; max-width: 100%;',
    '}',
    '.scw-bid-review-v2__cell-numbers {',
    '  display: flex; gap: 16px; margin-bottom: 10px;',
    '  font-size: 12px; color: #334155;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__cell-num {',
    '  display: inline-flex; align-items: baseline; gap: 5px;',
    '}',
    '.scw-bid-review-v2__cell-num label {',
    '  color: #64748b; font-size: 10px; font-weight: 600;',
    '}',
    '.scw-bid-review-v2__cell-desc {',
    '  color: #475569; font-size: 12px; line-height: 1.45;',
    '  overflow-wrap: anywhere; word-break: break-word;',
    '}',
    /* ── Inputs ────────────────────────────────────────────── */
    '.scw-bid-review-v2-input {',
    '  border: 1px solid #cbd5e1; border-radius: 4px;',
    '  background: #fff; color: #0f172a;',
    '  padding: 3px 6px; font-size: 12px;',
    '  font-family: inherit;',
    '  outline: none;',
    '  transition: border-color 0.15s, background 0.15s, box-shadow 0.15s;',
    '  width: 60px; box-sizing: border-box;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2-input--qty { width: 52px; }',
    '.scw-bid-review-v2-input--rate { width: 72px; }',
    '.scw-bid-review-v2-input--desc {',
    '  width: 100%; resize: vertical; min-height: 40px;',
    '  font-size: 11px; line-height: 1.4;',
    '  font-variant-numeric: normal;',
    '}',
    /* Hide number-input spinners — they crowd the small inputs */
    '.scw-bid-review-v2-input[type=number]::-webkit-inner-spin-button,',
    '.scw-bid-review-v2-input[type=number]::-webkit-outer-spin-button {',
    '  -webkit-appearance: none; margin: 0;',
    '}',
    '.scw-bid-review-v2-input[type=number] { -moz-appearance: textfield; }',
    '.scw-bid-review-v2-input:focus {',
    '  border-color: #295f91; box-shadow: 0 0 0 2px rgba(41,95,145,0.15);',
    '}',
    '.scw-bid-review-v2-input--saving {',
    '  background: #dcfce7 !important; border-color: #16a34a !important;',
    '}',
    '.scw-bid-review-v2-input--error {',
    '  background: #fee2e2 !important; border-color: #dc2626 !important;',
    '}',
    /* Cutover hook — flip CONFIG.replaceV1 to hide v1 entirely. */
    'html[data-scw-bid-review-v2-replace="1"] #bid-review-matrix {',
    '  display: none !important;',
    '}'
  ].join('\n');

  var style = document.createElement('style');
  style.id = ns.CONFIG.cssId;
  style.textContent = css;
  document.head.appendChild(style);
})();
/*** END BID REVIEW V2 — STYLES ***********************************************/
