/*** BID REVIEW V2 — STYLES ***************************************************
 *
 * Self-scoped CSS for the v2 panel. All rules nest under
 * .scw-bid-review-v2 so they cannot leak into v1 or the rest of the
 * scene.
 *
 * Banner mirrors worksheet-v2's WIP pill so the parallel build reads
 * consistently across the codebase.
 ****************************************************************************/
(function () {
  'use strict';

  var ns = window.SCW.bidReviewV2;
  if (!ns || !ns.CONFIG) return;

  if (document.getElementById(ns.CONFIG.cssId)) return;

  var css = [
    /* ── Container + WIP banner ─────────────────────────────── */
    '.scw-bid-review-v2 {',
    '  margin: 24px 0 32px;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;',
    '  color: #0f172a;',
    '}',
    '.scw-bid-review-v2-banner {',
    '  display: flex; align-items: center; gap: 8px;',
    '  padding: 10px 14px;',
    '  background: #f8fafc; border: 1px solid #e2e8f0;',
    '  border-radius: 8px 8px 0 0;',
    '  font-size: 13px; color: #334155;',
    '}',
    '.scw-bid-review-v2-pill {',
    '  display: inline-flex; align-items: center; gap: 4px;',
    '  padding: 2px 8px;',
    '  background: #6b21a8; color: #fff;',
    '  border-radius: 999px;',
    '  font-size: 11px; font-weight: 600; letter-spacing: 0.04em;',
    '  text-transform: uppercase;',
    '}',
    '.scw-bid-review-v2-count {',
    '  margin-left: auto;',
    '  color: #64748b; font-size: 12px;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2-body {',
    '  padding: 16px;',
    '  background: #fff;',
    '  border: 1px solid #e2e8f0; border-top: none;',
    '  border-radius: 0 0 8px 8px;',
    '  min-height: 80px;',
    '}',
    '.scw-bid-review-v2-empty {',
    '  color: #94a3b8; font-style: italic; font-size: 13px;',
    '  text-align: center; padding: 16px 0;',
    '}',
    /* ── SOW section card ───────────────────────────────────── */
    '.scw-bid-review-v2__sow {',
    '  margin-bottom: 32px;',
    '  border: 1px solid #cbd5e1; border-radius: 10px;',
    '  overflow: hidden; background: #fff;',
    '  box-shadow: 0 1px 2px rgba(15,23,42,0.04);',
    '}',
    '.scw-bid-review-v2__sow-header {',
    '  display: flex; align-items: baseline; gap: 12px;',
    '  padding: 14px 20px;',
    '  background: linear-gradient(180deg,#2d6aa3 0%,#295f91 100%);',
    '  color: #fff;',
    '  font-size: 15px; font-weight: 700; letter-spacing: 0.01em;',
    '}',
    '.scw-bid-review-v2__sow-name { flex: 0 0 auto; }',
    '.scw-bid-review-v2__sow-meta {',
    '  margin-left: auto;',
    '  font-size: 11px; font-weight: 500;',
    '  color: rgba(255,255,255,0.85);',
    '  font-variant-numeric: tabular-nums;',
    '}',
    /* ── Table + thead ─────────────────────────────────────── */
    /* table-layout:fixed + width:100% makes the bid columns divide the
       available width equally instead of each forcing a min-width (which
       overflows the page on multi-bid SOWs). Matches v1's column model.
       The min-width keeps it usable when the page is narrow — below that
       the body scrolls horizontally rather than crushing the columns. */
    '.scw-bid-review-v2__table {',
    '  width: 100%; border-collapse: separate; border-spacing: 0;',
    '  table-layout: fixed; min-width: 840px;',
    '  font-size: 12px;',
    '}',
    '.scw-bid-review-v2__th {',
    '  background: #f1f5f9; color: #475569; font-weight: 600;',
    '  text-align: left; padding: 14px 22px !important;',
    '  border-bottom: 1px solid #cbd5e1;',
    '  font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em;',
    '}',
    '.scw-bid-review-v2__th--label { width: 104px; }',
    '.scw-bid-review-v2__th--photos {',
    '  width: 150px; text-align: center;',
    '}',
    /* No explicit width — under table-layout:fixed the SOW column then
       shares the leftover space (after the fixed label + photos columns)
       equally with the bid columns, so SOW and each bid are the same
       width. */
    '.scw-bid-review-v2__th--sow {',
    '  background: #e3edf6; color: #295f91;',
    '  border-right: 2px solid #cbd5e1;',
    '}',
    /* ── L1 group header (MDF/IDF) ─────────────────────────── */
    '.scw-bid-review-v2__group-header { cursor: pointer; user-select: none; -webkit-user-select: none; }',
    '.scw-bid-review-v2__group-header td {',
    '  position: relative;',
    '  background: #f1f5f9; padding: 0;',
    '  font-weight: 700; font-size: 13px; color: #334155;',
    '  border-top: 1px solid #cbd5e1;',
    '  border-bottom: 1px solid #cbd5e1;',
    '  border-left: 4px solid #295f91;',
    '}',
    '.scw-bid-review-v2__group-header:first-child td { border-top: none; }',
    '.scw-bid-review-v2__group-header:hover td { background: #e8edf3; }',
    '.scw-bid-review-v2__grp-inner {',
    '  display: flex; align-items: center; gap: 10px;',
    '  padding: 12px 18px;',
    '}',
    '.scw-bid-review-v2__grp-chevron {',
    '  display: inline-flex; align-items: center; flex: 0 0 auto;',
    '  color: #295f91; transition: transform 220ms ease;',
    '}',
    '.scw-bid-review-v2__group-header--collapsed .scw-bid-review-v2__grp-chevron {',
    '  transform: rotate(-90deg);',
    '}',
    '.scw-bid-review-v2__grp-title { flex: 1 1 auto; }',
    '.scw-bid-review-v2__grp-count {',
    '  display: inline-block; padding: 2px 9px;',
    '  font-size: 11px; font-weight: 600; line-height: 1.4;',
    '  border-radius: 999px;',
    '  background: rgba(41,95,145,0.12);',
    '  border: 1px solid rgba(41,95,145,0.22);',
    '  color: #295f91;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    /* ── L2 sub-group header (proposal bucket) ─────────────── */
    '.scw-bid-review-v2__subgroup-header td {',
    '  background: #f8fafc; padding: 0;',
    '  border-bottom: 1px solid #e2e8f0;',
    '}',
    '.scw-bid-review-v2__subgrp-inner {',
    '  display: flex; align-items: center; gap: 8px;',
    '  padding: 9px 18px 9px 34px;',
    '}',
    '.scw-bid-review-v2__subgrp-title {',
    '  font-size: 11px; font-weight: 600; color: #475569;',
    '  text-transform: uppercase; letter-spacing: 0.04em;',
    '}',
    '.scw-bid-review-v2__subgrp-count {',
    '  display: inline-block; padding: 1px 7px;',
    '  font-size: 10px; font-weight: 600; line-height: 1.4;',
    '  border-radius: 999px; background: #e2e8f0; color: #64748b;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__row--hidden,',
    '.scw-bid-review-v2__subgroup-header--hidden { display: none !important; }',
    /* ── Data rows ─────────────────────────────────────────── */
    '.scw-bid-review-v2__row td {',
    '  border-bottom: 1px solid #e2e8f0;',
    '  vertical-align: top;',
    '}',
    '.scw-bid-review-v2__row--expandable { cursor: pointer; }',
    '.scw-bid-review-v2__row--expandable:hover td {',
    '  background-image: linear-gradient(rgba(41,95,145,0.04), rgba(41,95,145,0.04));',
    '}',
    '.scw-bid-review-v2__row--open td {',
    '  background-image: linear-gradient(rgba(41,95,145,0.06), rgba(41,95,145,0.06));',
    '  border-bottom-color: #295f91 !important;',
    '}',
    /* Expand row hosts worksheet-v2 card inline */
    '.scw-bid-review-v2__expand-row td {',
    '  background: #f1f5f9; padding: 12px 16px;',
    '  border-bottom: 1px solid #cbd5e1;',
    '  border-top: none;',
    '}',
    '.scw-bid-review-v2__expand-loading {',
    '  padding: 14px; color: #64748b; font-size: 12px;',
    '  text-align: center; font-style: italic;',
    '}',
    /* The injected worksheet-v2 card carries its own styles; just
       give it some breathing room inside the host cell. */
    '.scw-bid-review-v2__expand-cell .scw-ws-v2-card {',
    '  margin: 0; max-width: 100%;',
    '}',
    /* Side-by-side layout: photo viewer (left) + worksheet card (right).
       The photo column is collapsed until openWithPhoto() activates it. */
    /* Hide the data row while it's expanded — the panel header stands in
       for it, so SOW/bid data isn't shown twice. */
    '.scw-bid-review-v2__row[aria-expanded="true"] { display: none !important; }',
    /* ── Expand panel ──────────────────────────────────────── */
    '.scw-bid-review-v2__panel { width: 100%; }',
    '.scw-bid-review-v2__panel-header {',
    '  display: flex; align-items: center; gap: 10px;',
    '  padding: 4px 4px 12px; cursor: pointer;',
    '  border-bottom: 1px solid #e2e8f0; margin-bottom: 12px;',
    '}',
    '.scw-bid-review-v2__panel-title {',
    '  display: flex; align-items: baseline; gap: 10px;',
    '  flex: 1 1 auto; min-width: 0; flex-wrap: wrap;',
    '}',
    '.scw-bid-review-v2__panel-title-label {',
    '  font-weight: 700; font-size: 13px; color: #0f172a;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__panel-title-product {',
    '  font-weight: 600; font-size: 13px; color: #295f91;',
    '}',
    '.scw-bid-review-v2__panel-close {',
    '  flex: 0 0 auto; width: 26px; height: 26px; border-radius: 50%;',
    '  border: 1px solid #cbd5e1; background: #fff; color: #475569;',
    '  font-size: 17px; line-height: 1; cursor: pointer;',
    '  display: inline-flex; align-items: center; justify-content: center;',
    '}',
    '.scw-bid-review-v2__panel-close:hover { background: #f1f5f9; color: #0f172a; }',
    /* Side-by-side: photo viewer (collapsed until photos load) | the
       worksheet-v2 SOW editor (reflowed narrow, see overrides below) |
       bid details. Wraps on very narrow viewports. */
    '.scw-bid-review-v2__expand-flex {',
    '  display: flex; flex-wrap: wrap; align-items: flex-start;',
    '  gap: 14px; width: 100%;',
    '}',
    '.scw-bid-review-v2__panel-col--card { flex: 2 1 340px; min-width: 0; }',
    '.scw-bid-review-v2__panel-col--photo { display: none; }',
    '.scw-bid-review-v2__panel-col--photo-active {',
    '  display: flex; flex: 1 1 300px; max-width: 480px; min-width: 0;',
    '}',
    /* Bid details — compact comparison cards beside the editor. Cards
       wrap so multiple bids read across; the whole column wraps below
       the editor when the panel is too narrow to hold both. */
    '.scw-bid-review-v2__panel-col--bid {',
    '  flex: 1 1 260px; min-width: 0;',
    '  display: flex; flex-wrap: wrap; gap: 10px; align-content: flex-start;',
    '}',
    '.scw-bid-review-v2__bid-card {',
    '  flex: 1 1 180px; min-width: 160px; max-width: 320px;',
    '  background: #fff; border: 1px solid #e2e8f0; border-radius: 8px;',
    '  padding: 12px 14px; align-self: flex-start;',
    '}',
    '.scw-bid-review-v2__bid-card-label {',
    '  font-size: 11px; font-weight: 700; text-transform: uppercase;',
    '  letter-spacing: 0.04em; color: #295f91;',
    '  margin-bottom: 8px; padding-bottom: 6px;',
    '  border-bottom: 1px solid #e2e8f0;',
    '}',
    /* ── Narrow-editor reflow (scoped to the panel) ─────────────
       The worksheet-v2 summary row is a fixed ~930px 12-column grid that
       can't shrink. Inside the bid-review panel we reflow it into a
       wrapping form so it fits beside the bid cards: product + labor desc
       go full-width, the number inputs flow compactly under them. The
       grid-aligned column-header strip is hidden since it can't line up
       with a wrapped row. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-row--default,',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-row--cam,',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-row--services,',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-row--assumptions {',
    '  display: flex !important; flex-wrap: wrap !important;',
    /* top-align cells so the qty input lines up with the sub-bid/+Hrs/
       +Mat inputs even though those carry an extended total beneath. */
    '  align-items: flex-start !important; gap: 10px 12px !important;',
    '  position: relative !important; padding-right: 34px !important;',
    '}',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--product,',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--labor-desc {',
    '  flex: 1 1 100% !important; min-width: 0 !important;',
    '  grid-column: auto !important;',
    '}',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--num,',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--stack,',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--fee {',
    '  flex: 0 1 auto !important;',
    '}',
    /* SOW connection is relocated into the detail panel (above MDF/IDF) by
       decorateNarrowEditor — let it fill its detail field there. */
    '.scw-bid-review-v2__panel-col--card .scw-br-v2-sow-field .scw-ws-v2-cell--sow {',
    '  max-width: none !important; width: 100% !important;',
    '}',
    /* Stack the connection fields one per line so MDF/IDF sits directly
       under the SOW picker instead of wrapping into a second column. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-detail-zone--connections {',
    '  grid-template-columns: 1fr !important;',
    '}',
    /* SCW Notes full-width (Survey Notes is removed, so notes is a single
       field now) and the swapped-in textarea mirrors labor description. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-detail-notes {',
    '  grid-template-columns: 1fr !important;',
    '}',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-input--num { width: 72px !important; }',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--blank { display: none !important; }',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-col-header { display: none !important; }',
    /* Field labels above each reflowed input (the grid column-header is
       hidden, so labels are injected per-cell by decorateNarrowEditor).
       Centered over the input; a fixed height keeps the currency-glyph
       offset below deterministic. */
    '.scw-bid-review-v2__panel-col--card .scw-br-v2-flabel {',
    '  display: block; text-align: center; white-space: nowrap;',
    '  height: 11px; line-height: 11px; margin-bottom: 4px;',
    '  font: 700 9px system-ui, -apple-system, sans-serif;',
    '  text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8;',
    '}',
    /* Labor description is a wide field — its label reads better left. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--labor-desc .scw-br-v2-flabel {',
    '  text-align: left;',
    '}',
    /* The $ glyph is absolutely positioned to the cell top; the injected
       label pushes the input down, so drop the glyph to sit over it. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-currency-glyph {',
    '  top: 19px !important;',
    '}',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-stack-total { text-align: center !important; }',
    /* Existing / Exterior / Plenum chips inline, not stacked. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-cell--chips {',
    '  flex: 1 1 100% !important; display: flex !important;',
    '  flex-direction: row !important; flex-wrap: wrap !important;',
    '  gap: 6px !important; align-items: center !important;',
    '}',
    /* Pin the delete (trash) button to the editor row top-right instead
       of letting it flow mid-form. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-trash {',
    '  position: absolute !important; top: 0 !important; right: 0 !important;',
    '  margin: 0 !important; padding: 5px !important;',
    '  background: #fee2e2 !important; border: 1px solid #fecaca !important;',
    '  color: #dc2626 !important; border-radius: 6px !important;',
    '}',
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-trash:hover {',
    '  background: #fecaca !important; border-color: #f87171 !important;',
    '  color: #b91c1c !important;',
    '}',
    /* ── Photo viewer (ported from v1) ─────────────────────── */
    '.scw-bid-review-v2__photo-viewer {',
    '  flex: 1 1 auto; display: flex; flex-direction: column;',
    '  background: #0f172a; border-radius: 8px; overflow: hidden;',
    '  position: relative;',
    '  box-shadow: 0 16px 20px -10px rgba(2,132,199,0.385),',
    '              -10px 14px 18px -10px rgba(2,132,199,0.315),',
    '              10px 14px 18px -10px rgba(2,132,199,0.315);',
    '}',
    '.scw-bid-review-v2__photo-viewer-stage {',
    '  flex: 1 1 auto; min-height: 320px;',
    '  display: flex; align-items: center; justify-content: center;',
    '  overflow: hidden; position: relative; cursor: zoom-out;',
    '}',
    '.scw-bid-review-v2__photo-viewer-stage::after {',
    '  content: "Click to close"; position: absolute;',
    '  bottom: 8px; left: 50%; transform: translateX(-50%);',
    '  padding: 3px 10px; border-radius: 11px;',
    '  background: rgba(15,23,42,0.65); color: #fff;',
    '  font: 600 11px/1 system-ui, sans-serif;',
    '  opacity: 0; pointer-events: none; transition: opacity 120ms ease;',
    '}',
    '.scw-bid-review-v2__photo-viewer-stage:hover::after { opacity: 1; }',
    '.scw-bid-review-v2__photo-viewer-stage img,',
    '.kn-content .scw-bid-review-v2__photo-viewer-stage img {',
    '  display: block; max-width: 100%; max-height: 100%;',
    '  width: auto; height: auto; object-fit: contain;',
    '}',
    '.scw-bid-review-v2__photo-viewer-open {',
    '  position: absolute; top: 8px; left: 8px;',
    '  padding: 4px 10px; border-radius: 4px;',
    '  background: rgba(15,23,42,0.75); color: #fff;',
    '  border: 1px solid rgba(255,255,255,.25); cursor: pointer;',
    '  font: 600 11px/1 system-ui, sans-serif; text-decoration: none;',
    '  display: inline-flex; align-items: center; gap: 4px; z-index: 2;',
    '}',
    '.scw-bid-review-v2__photo-viewer-open:hover {',
    '  background: rgba(15,23,42,0.95); color: #fff;',
    '}',
    '.scw-bid-review-v2__photo-viewer-strip {',
    '  flex: 0 0 auto; display: flex; gap: 4px; padding: 6px 8px;',
    '  background: rgba(15,23,42,0.95); overflow-x: auto;',
    '}',
    '.scw-bid-review-v2__photo-viewer-thumb {',
    '  flex: 0 0 auto; width: 56px; height: 56px;',
    '  border-radius: 4px; border: 2px solid transparent;',
    '  overflow: hidden; cursor: pointer; background: #1e293b; padding: 0;',
    '}',
    '.scw-bid-review-v2__photo-viewer-thumb img,',
    '.kn-content .scw-bid-review-v2__photo-viewer-thumb img {',
    '  display: block; width: 100%; height: 100%;',
    '  object-fit: cover; max-width: none;',
    '}',
    '.scw-bid-review-v2__photo-viewer-thumb--active { border-color: #38bdf8; }',
    '.scw-bid-review-v2__lightbox {',
    '  position: fixed; inset: 0; z-index: 99999;',
    '  background: rgba(15,23,42,0.92); cursor: zoom-out;',
    '  display: flex; align-items: center; justify-content: center; padding: 32px;',
    '}',
    '.scw-bid-review-v2__lightbox img {',
    '  max-width: 95%; max-height: 95%; object-fit: contain;',
    '  border-radius: 6px; box-shadow: 0 8px 40px rgba(0,0,0,0.5);',
    '}',
    /* Line-item label cell (E-001, etc) */
    /* Caret gutter on the left; checkbox / label / totals stack with a
       clean gap so nothing is crammed together. */
    '.scw-bid-review-v2__row-label-cell {',
    '  position: relative;',
    '  padding: 16px 14px 16px 30px !important;',
    '  background: #f8fafc;',
    '  border-right: 1px solid #e2e8f0;',
    '  font-variant-numeric: tabular-nums;',
    '  vertical-align: top;',
    '  display: flex; flex-direction: column; align-items: flex-start; gap: 8px;',
    '}',
    '.scw-bid-review-v2__row-caret {',
    '  position: absolute; left: 7px; top: 15px;',
    '  display: inline-flex; color: #94a3b8;',
    '  transform: rotate(-90deg);', /* point right when closed */
    '  transition: transform 150ms ease, color 150ms ease;',
    '}',
    '.scw-bid-review-v2__row--expandable:hover .scw-bid-review-v2__row-caret {',
    '  color: #295f91;',
    '}',
    '.scw-bid-review-v2__panel-caret {',
    '  flex: 0 0 auto; display: inline-flex; color: #64748b;',
    '}',
    '.scw-bid-review-v2__row-label {',
    '  font-weight: 600; color: #0f172a; font-size: 12px;',
    '  margin-bottom: 8px;',
    '}',
    /* Per-row SOW totals stacked under the line label (v1 parity). */
    '.scw-bid-review-v2__row-totals {',
    '  display: flex; flex-direction: column; gap: 3px;',
    '}',
    '.scw-bid-review-v2__row-total {',
    '  display: flex; flex-direction: column; line-height: 1.2;',
    '}',
    '.scw-bid-review-v2__row-total-label {',
    '  font: 700 9px/1.2 system-ui, -apple-system, sans-serif;',
    '  text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8;',
    '}',
    '.scw-bid-review-v2__row-total-value {',
    '  font-size: 12px; font-weight: 600; color: #0f172a;',
    '}',
    '.scw-bid-review-v2__row-total--install .scw-bid-review-v2__row-total-value {',
    '  color: #295f91;',
    '}',
    /* Bulk-select checkbox in the leftmost grid cell. */
    '.scw-br-v2-rowselect {',
    '  display: block; width: 16px; height: 16px; margin: 0;',
    '  cursor: pointer; accent-color: #295f91; flex: 0 0 auto;',
    '}',
    /* Header variant — sits inline in the expand header, no stacking margin. */
    '.scw-bid-review-v2__panel-header .scw-br-v2-rowselect--header { margin: 0; }',
    /* The worksheet card carries its own bulk-select checkbox; hide it in
       the editor panel since selection happens from the grid column. */
    '.scw-bid-review-v2__panel-col--card .scw-ws-v2-select { display: none !important; }',
    /* ── SOW item cell — editable anchor column ────────────── */
    '.scw-bid-review-v2__sow-cell {',
    '  padding: 20px 22px !important;',
    '  background: #f4f8fc; border-right: 2px solid #cbd5e1;',
    '}',
    /* ── Photos column (v1 parity) ─────────────────────────── */
    '.scw-bid-review-v2__photos-cell {',
    '  padding: 8px 6px !important; vertical-align: top;',
    '  border-right: 1px solid #e2e8f0; background: #fff;',
    '}',
    '.scw-bid-review-v2__photos-stack {',
    '  display: flex; flex-direction: column; align-items: center; gap: 4px;',
    '}',
    '.scw-bid-review-v2__photos-thumb {',
    '  display: block; width: 136px; height: 136px;',
    '  border-radius: 6px; border: 1px solid #cbd5e1;',
    '  background: #fff; overflow: hidden; padding: 0;',
    '  transition: transform 100ms ease, box-shadow 100ms ease;',
    '  position: relative; cursor: zoom-in;',
    '}',
    '.scw-bid-review-v2__photos-thumb:hover {',
    '  transform: scale(1.02); box-shadow: 0 4px 14px rgba(0,0,0,.22); z-index: 2;',
    '}',
    '.scw-bid-review-v2__photos-thumb img,',
    '.kn-content .scw-bid-review-v2__photos-thumb img {',
    '  display: block; width: 100%; height: 100%;',
    '  object-fit: cover; max-width: none;',
    '}',
    '.scw-bid-review-v2__photos-more {',
    '  display: inline-flex; align-items: center; justify-content: center;',
    '  min-width: 32px; height: 22px; padding: 0 8px;',
    '  border-radius: 11px; background: #475569; color: #fff;',
    '  font-size: 11px; font-weight: 700; margin-top: 2px; cursor: pointer;',
    '}',
    '.scw-bid-review-v2__photos-empty {',
    '  font-size: 11px; color: #cbd5e1; text-align: center; padding: 10px 4px;',
    '}',
    '.scw-bid-review-v2__sow-cell--empty {',
    '  background: #fafafa; text-align: center; color: #cbd5e1;',
    '}',
    '.scw-bid-review-v2__sow-product {',
    '  font-weight: 600; font-size: 13px; color: #0f172a;',
    '  margin-bottom: 10px; line-height: 1.35;',
    '  overflow-wrap: anywhere; word-break: break-word;',
    '}',
    '.scw-bid-review-v2__sow-numbers {',
    '  display: flex; gap: 16px; align-items: center;',
    '  margin-bottom: 10px;',
    '}',
    '.scw-bid-review-v2__sow-num {',
    '  display: inline-flex; align-items: center; gap: 5px;',
    '  font-size: 12px; color: #334155;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__sow-num label {',
    '  color: #64748b; font-size: 10px;',
    '  font-weight: 600;',
    '}',
    '.scw-bid-review-v2__sow-desc-wrap { margin-top: 4px; }',
    /* ── Bid cells (read-only) ─────────────────────────────── */
    '.scw-bid-review-v2__cell {',
    '  padding: 20px 22px !important;',
    '  border-right: 1px solid #f1f5f9;',
    '  background: #fff;',
    '}',
    '.scw-bid-review-v2__cell:last-child { border-right: none; }',
    '.scw-bid-review-v2__cell--empty {',
    '  background: #fafafa; text-align: center; color: #cbd5e1;',
    '}',
    '.scw-bid-review-v2__cell-empty-mark { font-size: 18px; line-height: 1; }',
    '.scw-bid-review-v2__cell-product {',
    '  font-weight: 600; font-size: 13px; color: #0f172a;',
    '  margin-bottom: 10px; line-height: 1.35;',
    '  overflow-wrap: anywhere; word-break: break-word; max-width: 100%;',
    '}',
    '.scw-bid-review-v2__cell-numbers {',
    '  display: flex; gap: 16px; margin-bottom: 10px;',
    '  font-size: 12px; color: #334155;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__cell-num {',
    '  display: inline-flex; align-items: baseline; gap: 5px;',
    '}',
    '.scw-bid-review-v2__cell-num label {',
    '  color: #64748b; font-size: 10px; font-weight: 600;',
    '}',
    '.scw-bid-review-v2__cell-desc {',
    '  color: #475569; font-size: 12px; line-height: 1.45;',
    '  overflow-wrap: anywhere; word-break: break-word;',
    '}',
    /* ── Inputs ────────────────────────────────────────────── */
    '.scw-bid-review-v2-input {',
    '  border: 1px solid #cbd5e1; border-radius: 4px;',
    '  background: #fff; color: #0f172a;',
    '  padding: 3px 6px; font-size: 12px;',
    '  font-family: inherit;',
    '  outline: none;',
    '  transition: border-color 0.15s, background 0.15s, box-shadow 0.15s;',
    '  width: 60px; box-sizing: border-box;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2-input--qty { width: 52px; }',
    '.scw-bid-review-v2-input--rate { width: 72px; }',
    '.scw-bid-review-v2-input--desc {',
    '  width: 100%; resize: vertical; min-height: 40px;',
    '  font-size: 11px; line-height: 1.4;',
    '  font-variant-numeric: normal;',
    '}',
    /* Hide number-input spinners — they crowd the small inputs */
    '.scw-bid-review-v2-input[type=number]::-webkit-inner-spin-button,',
    '.scw-bid-review-v2-input[type=number]::-webkit-outer-spin-button {',
    '  -webkit-appearance: none; margin: 0;',
    '}',
    '.scw-bid-review-v2-input[type=number] { -moz-appearance: textfield; }',
    '.scw-bid-review-v2-input:focus {',
    '  border-color: #295f91; box-shadow: 0 0 0 2px rgba(41,95,145,0.15);',
    '}',
    '.scw-bid-review-v2-input--saving {',
    '  background: #dcfce7 !important; border-color: #16a34a !important;',
    '}',
    '.scw-bid-review-v2-input--error {',
    '  background: #fee2e2 !important; border-color: #dc2626 !important;',
    '}',
    /* Cutover hook — flip CONFIG.replaceV1 to hide v1 entirely. */
    'html[data-scw-bid-review-v2-replace="1"] #bid-review-matrix {',
    '  display: none !important;',
    '}'
  ].join('\n');

  var style = document.createElement('style');
  style.id = ns.CONFIG.cssId;
  style.textContent = css;
  document.head.appendChild(style);
})();
/*** END BID REVIEW V2 — STYLES ***********************************************/
