/*** BID REVIEW V2 — STYLES ***************************************************
 *
 * Self-scoped CSS for the v2 panel. All rules nest under
 * .scw-bid-review-v2 so they cannot leak into v1 or the rest of the
 * scene.
 *
 * Banner mirrors worksheet-v2's WIP pill so the parallel build reads
 * consistently across the codebase.
 ****************************************************************************/
(function () {
  'use strict';

  var ns = window.SCW.bidReviewV2;
  if (!ns || !ns.CONFIG) return;

  if (document.getElementById(ns.CONFIG.cssId)) return;

  var css = [
    '.scw-bid-review-v2 {',
    '  margin: 24px 0 32px;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;',
    '  color: #0f172a;',
    '}',
    '.scw-bid-review-v2-banner {',
    '  display: flex; align-items: center; gap: 8px;',
    '  padding: 10px 14px;',
    '  background: #f8fafc; border: 1px solid #e2e8f0;',
    '  border-radius: 8px 8px 0 0;',
    '  font-size: 13px; color: #334155;',
    '}',
    '.scw-bid-review-v2-pill {',
    '  display: inline-flex; align-items: center; gap: 4px;',
    '  padding: 2px 8px;',
    '  background: #6b21a8; color: #fff;',
    '  border-radius: 999px;',
    '  font-size: 11px; font-weight: 600; letter-spacing: 0.04em;',
    '  text-transform: uppercase;',
    '}',
    '.scw-bid-review-v2-count {',
    '  margin-left: auto;',
    '  color: #64748b; font-size: 12px;',
    '}',
    '.scw-bid-review-v2-body {',
    '  padding: 16px;',
    '  background: #fff;',
    '  border: 1px solid #e2e8f0; border-top: none;',
    '  border-radius: 0 0 8px 8px;',
    '  min-height: 80px;',
    '}',
    '.scw-bid-review-v2-empty {',
    '  color: #94a3b8; font-style: italic; font-size: 13px;',
    '  text-align: center; padding: 16px 0;',
    '}',
    /* ── SOW sections + grid table ─────────────────────────── */
    '.scw-bid-review-v2__sow {',
    '  margin-bottom: 24px;',
    '  border: 1px solid #e2e8f0; border-radius: 8px;',
    '  overflow: hidden; background: #fff;',
    '}',
    '.scw-bid-review-v2__sow-header {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 8px 12px; background: #295f91; color: #fff;',
    '  font-size: 13px; font-weight: 600;',
    '}',
    '.scw-bid-review-v2__sow-meta {',
    '  font-size: 11px; font-weight: 400; opacity: 0.85;',
    '}',
    '.scw-bid-review-v2__table {',
    '  width: 100%; border-collapse: collapse; font-size: 12px;',
    '}',
    '.scw-bid-review-v2__th {',
    '  background: #f1f5f9; color: #334155; font-weight: 600;',
    '  text-align: left; padding: 6px 8px;',
    '  border-bottom: 1px solid #cbd5e1;',
    '}',
    '.scw-bid-review-v2__th--label { width: 220px; }',
    /* ── L1 (MDF/IDF) + L2 (proposal bucket) header rows ───── */
    '.scw-bid-review-v2__l1-row { background: #fef3e7; }',
    '.scw-bid-review-v2__l1-cell {',
    '  padding: 6px 10px; border-top: 1px solid #f59e0b;',
    '  border-bottom: 1px solid #f59e0b;',
    '  color: #7c2d12; font-weight: 700; font-size: 12px;',
    '  text-transform: uppercase; letter-spacing: 0.04em;',
    '  display: flex; align-items: center; gap: 8px;',
    '}',
    '.scw-bid-review-v2__l1-count {',
    '  margin-left: auto; font-size: 11px; font-weight: 600;',
    '  background: #f59e0b; color: #fff; padding: 1px 8px; border-radius: 999px;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__l2-row { background: #f8fafc; }',
    '.scw-bid-review-v2__l2-cell {',
    '  padding: 4px 10px 4px 24px;',
    '  border-top: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0;',
    '  color: #0f4c75; font-weight: 600; font-size: 11px;',
    '  display: flex; align-items: center; gap: 6px;',
    '}',
    '.scw-bid-review-v2__l2-count {',
    '  margin-left: auto; font-size: 10px; color: #64748b;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.scw-bid-review-v2__row { border-bottom: 1px solid #e2e8f0; }',
    '.scw-bid-review-v2__row:last-child { border-bottom: none; }',
    '.scw-bid-review-v2__row-label-cell {',
    '  padding: 8px; vertical-align: top; background: #f8fafc;',
    '  border-right: 1px solid #e2e8f0;',
    '}',
    '.scw-bid-review-v2__row-label {',
    '  font-weight: 600; color: #0f172a; font-size: 12px;',
    '}',
    '.scw-bid-review-v2__row-product {',
    '  color: #64748b; font-size: 11px; margin-top: 2px;',
    '}',
    /* ── Bid cells ─────────────────────────────────────────── */
    '.scw-bid-review-v2__cell {',
    '  padding: 6px 8px; vertical-align: top;',
    '  border-right: 1px solid #f1f5f9; min-width: 160px;',
    '}',
    '.scw-bid-review-v2__cell:last-child { border-right: none; }',
    '.scw-bid-review-v2__cell--empty { background: #fafafa; text-align: center; color: #cbd5e1; }',
    '.scw-bid-review-v2__cell-empty-mark { font-size: 18px; }',
    '.scw-bid-review-v2__cell-line {',
    '  display: flex; align-items: center; gap: 6px; margin-bottom: 4px;',
    '}',
    '.scw-bid-review-v2__cell-label {',
    '  font-size: 10px; color: #64748b; min-width: 28px;',
    '  text-transform: uppercase; letter-spacing: 0.04em;',
    '}',
    '.scw-bid-review-v2__cell-ext {',
    '  font-variant-numeric: tabular-nums; font-weight: 600; color: #0f172a;',
    '}',
    '.scw-bid-review-v2__cell-desc-wrap { margin-top: 4px; }',
    /* ── Inputs (the headline: not Knack inline-edit) ─────── */
    '.scw-bid-review-v2-input {',
    '  border: 1px solid #cbd5e1; border-radius: 4px;',
    '  background: #fff; color: #0f172a;',
    '  padding: 3px 6px; font-size: 12px;',
    '  font-family: inherit;',
    '  outline: none; transition: border-color 0.15s, background 0.15s;',
    '  width: 80px; box-sizing: border-box;',
    '}',
    '.scw-bid-review-v2-input--desc {',
    '  width: 100%; resize: vertical; min-height: 36px;',
    '  font-size: 11px; line-height: 1.4;',
    '}',
    '.scw-bid-review-v2-input:focus {',
    '  border-color: #295f91; box-shadow: 0 0 0 2px rgba(41,95,145,0.15);',
    '}',
    '.scw-bid-review-v2-input--saving {',
    '  background: #dcfce7 !important; border-color: #16a34a !important;',
    '}',
    '.scw-bid-review-v2-input--error {',
    '  background: #fee2e2 !important; border-color: #dc2626 !important;',
    '}',
    '/* Cutover: when CONFIG.replaceV1 is true, init.js stamps this',
    '   attribute on <html> and v1’s grid mount is hidden. */',
    'html[data-scw-bid-review-v2-replace="1"] #bid-review-matrix {',
    '  display: none !important;',
    '}'
  ].join('\n');

  var style = document.createElement('style');
  style.id = ns.CONFIG.cssId;
  style.textContent = css;
  document.head.appendChild(style);
})();
/*** END BID REVIEW V2 — STYLES ***********************************************/
